// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"context"

	"github.com/go-tangra/go-tangra-warden/internal/data/ent/auditlog"
	"github.com/go-tangra/go-tangra-warden/internal/data/ent/folder"
	"github.com/go-tangra/go-tangra-warden/internal/data/ent/permission"
	"github.com/go-tangra/go-tangra-warden/internal/data/ent/schema"
	"github.com/go-tangra/go-tangra-warden/internal/data/ent/secret"
	"github.com/go-tangra/go-tangra-warden/internal/data/ent/secretversion"

	"entgo.io/ent"
	"entgo.io/ent/privacy"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	auditlogMixin := schema.AuditLog{}.Mixin()
	auditlog.Policy = privacy.NewPolicies(auditlogMixin[2], schema.AuditLog{})
	auditlog.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := auditlog.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	auditlogMixinFields0 := auditlogMixin[0].Fields()
	_ = auditlogMixinFields0
	auditlogMixinFields2 := auditlogMixin[2].Fields()
	_ = auditlogMixinFields2
	auditlogFields := schema.AuditLog{}.Fields()
	_ = auditlogFields
	// auditlogDescTenantID is the schema descriptor for tenant_id field.
	auditlogDescTenantID := auditlogMixinFields2[0].Descriptor()
	// auditlog.DefaultTenantID holds the default value on creation for the tenant_id field.
	auditlog.DefaultTenantID = auditlogDescTenantID.Default.(uint32)
	// auditlogDescAuditID is the schema descriptor for audit_id field.
	auditlogDescAuditID := auditlogFields[0].Descriptor()
	// auditlog.AuditIDValidator is a validator for the "audit_id" field. It is called by the builders before save.
	auditlog.AuditIDValidator = auditlogDescAuditID.Validators[0].(func(string) error)
	// auditlogDescOperation is the schema descriptor for operation field.
	auditlogDescOperation := auditlogFields[2].Descriptor()
	// auditlog.OperationValidator is a validator for the "operation" field. It is called by the builders before save.
	auditlog.OperationValidator = auditlogDescOperation.Validators[0].(func(string) error)
	// auditlogDescServiceName is the schema descriptor for service_name field.
	auditlogDescServiceName := auditlogFields[3].Descriptor()
	// auditlog.DefaultServiceName holds the default value on creation for the service_name field.
	auditlog.DefaultServiceName = auditlogDescServiceName.Default.(string)
	// auditlogDescIsAuthenticated is the schema descriptor for is_authenticated field.
	auditlogDescIsAuthenticated := auditlogFields[8].Descriptor()
	// auditlog.DefaultIsAuthenticated holds the default value on creation for the is_authenticated field.
	auditlog.DefaultIsAuthenticated = auditlogDescIsAuthenticated.Default.(bool)
	// auditlogDescSuccess is the schema descriptor for success field.
	auditlogDescSuccess := auditlogFields[9].Descriptor()
	// auditlog.DefaultSuccess holds the default value on creation for the success field.
	auditlog.DefaultSuccess = auditlogDescSuccess.Default.(bool)
	// auditlogDescLatencyMs is the schema descriptor for latency_ms field.
	auditlogDescLatencyMs := auditlogFields[12].Descriptor()
	// auditlog.DefaultLatencyMs holds the default value on creation for the latency_ms field.
	auditlog.DefaultLatencyMs = auditlogDescLatencyMs.Default.(int64)
	// auditlogDescID is the schema descriptor for id field.
	auditlogDescID := auditlogMixinFields0[0].Descriptor()
	// auditlog.IDValidator is a validator for the "id" field. It is called by the builders before save.
	auditlog.IDValidator = auditlogDescID.Validators[0].(func(uint32) error)
	folderMixin := schema.Folder{}.Mixin()
	folder.Policy = privacy.NewPolicies(folderMixin[2], schema.Folder{})
	folder.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := folder.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	folderMixinFields2 := folderMixin[2].Fields()
	_ = folderMixinFields2
	folderFields := schema.Folder{}.Fields()
	_ = folderFields
	// folderDescTenantID is the schema descriptor for tenant_id field.
	folderDescTenantID := folderMixinFields2[0].Descriptor()
	// folder.DefaultTenantID holds the default value on creation for the tenant_id field.
	folder.DefaultTenantID = folderDescTenantID.Default.(uint32)
	// folderDescName is the schema descriptor for name field.
	folderDescName := folderFields[2].Descriptor()
	// folder.NameValidator is a validator for the "name" field. It is called by the builders before save.
	folder.NameValidator = func() func(string) error {
		validators := folderDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// folderDescPath is the schema descriptor for path field.
	folderDescPath := folderFields[3].Descriptor()
	// folder.PathValidator is a validator for the "path" field. It is called by the builders before save.
	folder.PathValidator = func() func(string) error {
		validators := folderDescPath.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(_path string) error {
			for _, fn := range fns {
				if err := fn(_path); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// folderDescDescription is the schema descriptor for description field.
	folderDescDescription := folderFields[4].Descriptor()
	// folder.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	folder.DescriptionValidator = folderDescDescription.Validators[0].(func(string) error)
	// folderDescDepth is the schema descriptor for depth field.
	folderDescDepth := folderFields[5].Descriptor()
	// folder.DefaultDepth holds the default value on creation for the depth field.
	folder.DefaultDepth = folderDescDepth.Default.(int32)
	// folderDescID is the schema descriptor for id field.
	folderDescID := folderFields[0].Descriptor()
	// folder.IDValidator is a validator for the "id" field. It is called by the builders before save.
	folder.IDValidator = folderDescID.Validators[0].(func(string) error)
	permissionMixin := schema.Permission{}.Mixin()
	permission.Policy = privacy.NewPolicies(permissionMixin[1], schema.Permission{})
	permission.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := permission.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	permissionMixinFields1 := permissionMixin[1].Fields()
	_ = permissionMixinFields1
	permissionFields := schema.Permission{}.Fields()
	_ = permissionFields
	// permissionDescTenantID is the schema descriptor for tenant_id field.
	permissionDescTenantID := permissionMixinFields1[0].Descriptor()
	// permission.DefaultTenantID holds the default value on creation for the tenant_id field.
	permission.DefaultTenantID = permissionDescTenantID.Default.(uint32)
	// permissionDescResourceID is the schema descriptor for resource_id field.
	permissionDescResourceID := permissionFields[1].Descriptor()
	// permission.ResourceIDValidator is a validator for the "resource_id" field. It is called by the builders before save.
	permission.ResourceIDValidator = func() func(string) error {
		validators := permissionDescResourceID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(resource_id string) error {
			for _, fn := range fns {
				if err := fn(resource_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// permissionDescSubjectID is the schema descriptor for subject_id field.
	permissionDescSubjectID := permissionFields[4].Descriptor()
	// permission.SubjectIDValidator is a validator for the "subject_id" field. It is called by the builders before save.
	permission.SubjectIDValidator = func() func(string) error {
		validators := permissionDescSubjectID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(subject_id string) error {
			for _, fn := range fns {
				if err := fn(subject_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	secretMixin := schema.Secret{}.Mixin()
	secret.Policy = privacy.NewPolicies(secretMixin[3], schema.Secret{})
	secret.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := secret.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	secretMixinFields3 := secretMixin[3].Fields()
	_ = secretMixinFields3
	secretFields := schema.Secret{}.Fields()
	_ = secretFields
	// secretDescTenantID is the schema descriptor for tenant_id field.
	secretDescTenantID := secretMixinFields3[0].Descriptor()
	// secret.DefaultTenantID holds the default value on creation for the tenant_id field.
	secret.DefaultTenantID = secretDescTenantID.Default.(uint32)
	// secretDescName is the schema descriptor for name field.
	secretDescName := secretFields[2].Descriptor()
	// secret.NameValidator is a validator for the "name" field. It is called by the builders before save.
	secret.NameValidator = func() func(string) error {
		validators := secretDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// secretDescUsername is the schema descriptor for username field.
	secretDescUsername := secretFields[3].Descriptor()
	// secret.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	secret.UsernameValidator = secretDescUsername.Validators[0].(func(string) error)
	// secretDescHostURL is the schema descriptor for host_url field.
	secretDescHostURL := secretFields[4].Descriptor()
	// secret.HostURLValidator is a validator for the "host_url" field. It is called by the builders before save.
	secret.HostURLValidator = secretDescHostURL.Validators[0].(func(string) error)
	// secretDescVaultPath is the schema descriptor for vault_path field.
	secretDescVaultPath := secretFields[5].Descriptor()
	// secret.VaultPathValidator is a validator for the "vault_path" field. It is called by the builders before save.
	secret.VaultPathValidator = secretDescVaultPath.Validators[0].(func(string) error)
	// secretDescCurrentVersion is the schema descriptor for current_version field.
	secretDescCurrentVersion := secretFields[6].Descriptor()
	// secret.DefaultCurrentVersion holds the default value on creation for the current_version field.
	secret.DefaultCurrentVersion = secretDescCurrentVersion.Default.(int32)
	// secretDescDescription is the schema descriptor for description field.
	secretDescDescription := secretFields[8].Descriptor()
	// secret.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	secret.DescriptionValidator = secretDescDescription.Validators[0].(func(string) error)
	// secretDescID is the schema descriptor for id field.
	secretDescID := secretFields[0].Descriptor()
	// secret.IDValidator is a validator for the "id" field. It is called by the builders before save.
	secret.IDValidator = secretDescID.Validators[0].(func(string) error)
	secretversionFields := schema.SecretVersion{}.Fields()
	_ = secretversionFields
	// secretversionDescSecretID is the schema descriptor for secret_id field.
	secretversionDescSecretID := secretversionFields[0].Descriptor()
	// secretversion.SecretIDValidator is a validator for the "secret_id" field. It is called by the builders before save.
	secretversion.SecretIDValidator = secretversionDescSecretID.Validators[0].(func(string) error)
	// secretversionDescVersionNumber is the schema descriptor for version_number field.
	secretversionDescVersionNumber := secretversionFields[1].Descriptor()
	// secretversion.VersionNumberValidator is a validator for the "version_number" field. It is called by the builders before save.
	secretversion.VersionNumberValidator = secretversionDescVersionNumber.Validators[0].(func(int32) error)
	// secretversionDescVaultPath is the schema descriptor for vault_path field.
	secretversionDescVaultPath := secretversionFields[2].Descriptor()
	// secretversion.VaultPathValidator is a validator for the "vault_path" field. It is called by the builders before save.
	secretversion.VaultPathValidator = secretversionDescVaultPath.Validators[0].(func(string) error)
	// secretversionDescComment is the schema descriptor for comment field.
	secretversionDescComment := secretversionFields[3].Descriptor()
	// secretversion.CommentValidator is a validator for the "comment" field. It is called by the builders before save.
	secretversion.CommentValidator = secretversionDescComment.Validators[0].(func(string) error)
	// secretversionDescChecksum is the schema descriptor for checksum field.
	secretversionDescChecksum := secretversionFields[4].Descriptor()
	// secretversion.ChecksumValidator is a validator for the "checksum" field. It is called by the builders before save.
	secretversion.ChecksumValidator = func() func(string) error {
		validators := secretversionDescChecksum.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(checksum string) error {
			for _, fn := range fns {
				if err := fn(checksum); err != nil {
					return err
				}
			}
			return nil
		}
	}()
}

const (
	Version = "v0.14.5"                                         // Version of ent codegen.
	Sum     = "h1:Rj2WOYJtCkWyFo6a+5wB3EfBRP0rnx1fMk6gGA0UUe4=" // Sum of ent codegen.
)
