// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-warden/internal/data/ent/auditlog"
)

// AuditLogCreate is the builder for creating a AuditLog entity.
type AuditLogCreate struct {
	config
	mutation *AuditLogMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (_c *AuditLogCreate) SetCreateTime(v time.Time) *AuditLogCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillableCreateTime(v *time.Time) *AuditLogCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *AuditLogCreate) SetUpdateTime(v time.Time) *AuditLogCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillableUpdateTime(v *time.Time) *AuditLogCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetDeleteTime sets the "delete_time" field.
func (_c *AuditLogCreate) SetDeleteTime(v time.Time) *AuditLogCreate {
	_c.mutation.SetDeleteTime(v)
	return _c
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillableDeleteTime(v *time.Time) *AuditLogCreate {
	if v != nil {
		_c.SetDeleteTime(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *AuditLogCreate) SetTenantID(v uint32) *AuditLogCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillableTenantID(v *uint32) *AuditLogCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetAuditID sets the "audit_id" field.
func (_c *AuditLogCreate) SetAuditID(v string) *AuditLogCreate {
	_c.mutation.SetAuditID(v)
	return _c
}

// SetRequestID sets the "request_id" field.
func (_c *AuditLogCreate) SetRequestID(v string) *AuditLogCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillableRequestID(v *string) *AuditLogCreate {
	if v != nil {
		_c.SetRequestID(*v)
	}
	return _c
}

// SetOperation sets the "operation" field.
func (_c *AuditLogCreate) SetOperation(v string) *AuditLogCreate {
	_c.mutation.SetOperation(v)
	return _c
}

// SetServiceName sets the "service_name" field.
func (_c *AuditLogCreate) SetServiceName(v string) *AuditLogCreate {
	_c.mutation.SetServiceName(v)
	return _c
}

// SetNillableServiceName sets the "service_name" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillableServiceName(v *string) *AuditLogCreate {
	if v != nil {
		_c.SetServiceName(*v)
	}
	return _c
}

// SetClientID sets the "client_id" field.
func (_c *AuditLogCreate) SetClientID(v string) *AuditLogCreate {
	_c.mutation.SetClientID(v)
	return _c
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillableClientID(v *string) *AuditLogCreate {
	if v != nil {
		_c.SetClientID(*v)
	}
	return _c
}

// SetClientCommonName sets the "client_common_name" field.
func (_c *AuditLogCreate) SetClientCommonName(v string) *AuditLogCreate {
	_c.mutation.SetClientCommonName(v)
	return _c
}

// SetNillableClientCommonName sets the "client_common_name" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillableClientCommonName(v *string) *AuditLogCreate {
	if v != nil {
		_c.SetClientCommonName(*v)
	}
	return _c
}

// SetClientOrganization sets the "client_organization" field.
func (_c *AuditLogCreate) SetClientOrganization(v string) *AuditLogCreate {
	_c.mutation.SetClientOrganization(v)
	return _c
}

// SetNillableClientOrganization sets the "client_organization" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillableClientOrganization(v *string) *AuditLogCreate {
	if v != nil {
		_c.SetClientOrganization(*v)
	}
	return _c
}

// SetClientSerialNumber sets the "client_serial_number" field.
func (_c *AuditLogCreate) SetClientSerialNumber(v string) *AuditLogCreate {
	_c.mutation.SetClientSerialNumber(v)
	return _c
}

// SetNillableClientSerialNumber sets the "client_serial_number" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillableClientSerialNumber(v *string) *AuditLogCreate {
	if v != nil {
		_c.SetClientSerialNumber(*v)
	}
	return _c
}

// SetIsAuthenticated sets the "is_authenticated" field.
func (_c *AuditLogCreate) SetIsAuthenticated(v bool) *AuditLogCreate {
	_c.mutation.SetIsAuthenticated(v)
	return _c
}

// SetNillableIsAuthenticated sets the "is_authenticated" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillableIsAuthenticated(v *bool) *AuditLogCreate {
	if v != nil {
		_c.SetIsAuthenticated(*v)
	}
	return _c
}

// SetSuccess sets the "success" field.
func (_c *AuditLogCreate) SetSuccess(v bool) *AuditLogCreate {
	_c.mutation.SetSuccess(v)
	return _c
}

// SetNillableSuccess sets the "success" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillableSuccess(v *bool) *AuditLogCreate {
	if v != nil {
		_c.SetSuccess(*v)
	}
	return _c
}

// SetErrorCode sets the "error_code" field.
func (_c *AuditLogCreate) SetErrorCode(v int32) *AuditLogCreate {
	_c.mutation.SetErrorCode(v)
	return _c
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillableErrorCode(v *int32) *AuditLogCreate {
	if v != nil {
		_c.SetErrorCode(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *AuditLogCreate) SetErrorMessage(v string) *AuditLogCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillableErrorMessage(v *string) *AuditLogCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetLatencyMs sets the "latency_ms" field.
func (_c *AuditLogCreate) SetLatencyMs(v int64) *AuditLogCreate {
	_c.mutation.SetLatencyMs(v)
	return _c
}

// SetNillableLatencyMs sets the "latency_ms" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillableLatencyMs(v *int64) *AuditLogCreate {
	if v != nil {
		_c.SetLatencyMs(*v)
	}
	return _c
}

// SetPeerAddress sets the "peer_address" field.
func (_c *AuditLogCreate) SetPeerAddress(v string) *AuditLogCreate {
	_c.mutation.SetPeerAddress(v)
	return _c
}

// SetNillablePeerAddress sets the "peer_address" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillablePeerAddress(v *string) *AuditLogCreate {
	if v != nil {
		_c.SetPeerAddress(*v)
	}
	return _c
}

// SetGeoLocation sets the "geo_location" field.
func (_c *AuditLogCreate) SetGeoLocation(v map[string]string) *AuditLogCreate {
	_c.mutation.SetGeoLocation(v)
	return _c
}

// SetLogHash sets the "log_hash" field.
func (_c *AuditLogCreate) SetLogHash(v string) *AuditLogCreate {
	_c.mutation.SetLogHash(v)
	return _c
}

// SetNillableLogHash sets the "log_hash" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillableLogHash(v *string) *AuditLogCreate {
	if v != nil {
		_c.SetLogHash(*v)
	}
	return _c
}

// SetSignature sets the "signature" field.
func (_c *AuditLogCreate) SetSignature(v []byte) *AuditLogCreate {
	_c.mutation.SetSignature(v)
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *AuditLogCreate) SetMetadata(v map[string]string) *AuditLogCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetID sets the "id" field.
func (_c *AuditLogCreate) SetID(v uint32) *AuditLogCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the AuditLogMutation object of the builder.
func (_c *AuditLogCreate) Mutation() *AuditLogMutation {
	return _c.mutation
}

// Save creates the AuditLog in the database.
func (_c *AuditLogCreate) Save(ctx context.Context) (*AuditLog, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AuditLogCreate) SaveX(ctx context.Context) *AuditLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuditLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuditLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AuditLogCreate) defaults() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := auditlog.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.ServiceName(); !ok {
		v := auditlog.DefaultServiceName
		_c.mutation.SetServiceName(v)
	}
	if _, ok := _c.mutation.IsAuthenticated(); !ok {
		v := auditlog.DefaultIsAuthenticated
		_c.mutation.SetIsAuthenticated(v)
	}
	if _, ok := _c.mutation.Success(); !ok {
		v := auditlog.DefaultSuccess
		_c.mutation.SetSuccess(v)
	}
	if _, ok := _c.mutation.LatencyMs(); !ok {
		v := auditlog.DefaultLatencyMs
		_c.mutation.SetLatencyMs(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *AuditLogCreate) check() error {
	if _, ok := _c.mutation.AuditID(); !ok {
		return &ValidationError{Name: "audit_id", err: errors.New(`ent: missing required field "AuditLog.audit_id"`)}
	}
	if v, ok := _c.mutation.AuditID(); ok {
		if err := auditlog.AuditIDValidator(v); err != nil {
			return &ValidationError{Name: "audit_id", err: fmt.Errorf(`ent: validator failed for field "AuditLog.audit_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Operation(); !ok {
		return &ValidationError{Name: "operation", err: errors.New(`ent: missing required field "AuditLog.operation"`)}
	}
	if v, ok := _c.mutation.Operation(); ok {
		if err := auditlog.OperationValidator(v); err != nil {
			return &ValidationError{Name: "operation", err: fmt.Errorf(`ent: validator failed for field "AuditLog.operation": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ServiceName(); !ok {
		return &ValidationError{Name: "service_name", err: errors.New(`ent: missing required field "AuditLog.service_name"`)}
	}
	if _, ok := _c.mutation.IsAuthenticated(); !ok {
		return &ValidationError{Name: "is_authenticated", err: errors.New(`ent: missing required field "AuditLog.is_authenticated"`)}
	}
	if _, ok := _c.mutation.Success(); !ok {
		return &ValidationError{Name: "success", err: errors.New(`ent: missing required field "AuditLog.success"`)}
	}
	if _, ok := _c.mutation.LatencyMs(); !ok {
		return &ValidationError{Name: "latency_ms", err: errors.New(`ent: missing required field "AuditLog.latency_ms"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := auditlog.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "AuditLog.id": %w`, err)}
		}
	}
	return nil
}

func (_c *AuditLogCreate) sqlSave(ctx context.Context) (*AuditLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint32(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AuditLogCreate) createSpec() (*AuditLog, *sqlgraph.CreateSpec) {
	var (
		_node = &AuditLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(auditlog.Table, sqlgraph.NewFieldSpec(auditlog.FieldID, field.TypeUint32))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(auditlog.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = &value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(auditlog.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = &value
	}
	if value, ok := _c.mutation.DeleteTime(); ok {
		_spec.SetField(auditlog.FieldDeleteTime, field.TypeTime, value)
		_node.DeleteTime = &value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(auditlog.FieldTenantID, field.TypeUint32, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.AuditID(); ok {
		_spec.SetField(auditlog.FieldAuditID, field.TypeString, value)
		_node.AuditID = value
	}
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(auditlog.FieldRequestID, field.TypeString, value)
		_node.RequestID = value
	}
	if value, ok := _c.mutation.Operation(); ok {
		_spec.SetField(auditlog.FieldOperation, field.TypeString, value)
		_node.Operation = value
	}
	if value, ok := _c.mutation.ServiceName(); ok {
		_spec.SetField(auditlog.FieldServiceName, field.TypeString, value)
		_node.ServiceName = value
	}
	if value, ok := _c.mutation.ClientID(); ok {
		_spec.SetField(auditlog.FieldClientID, field.TypeString, value)
		_node.ClientID = value
	}
	if value, ok := _c.mutation.ClientCommonName(); ok {
		_spec.SetField(auditlog.FieldClientCommonName, field.TypeString, value)
		_node.ClientCommonName = value
	}
	if value, ok := _c.mutation.ClientOrganization(); ok {
		_spec.SetField(auditlog.FieldClientOrganization, field.TypeString, value)
		_node.ClientOrganization = value
	}
	if value, ok := _c.mutation.ClientSerialNumber(); ok {
		_spec.SetField(auditlog.FieldClientSerialNumber, field.TypeString, value)
		_node.ClientSerialNumber = value
	}
	if value, ok := _c.mutation.IsAuthenticated(); ok {
		_spec.SetField(auditlog.FieldIsAuthenticated, field.TypeBool, value)
		_node.IsAuthenticated = value
	}
	if value, ok := _c.mutation.Success(); ok {
		_spec.SetField(auditlog.FieldSuccess, field.TypeBool, value)
		_node.Success = value
	}
	if value, ok := _c.mutation.ErrorCode(); ok {
		_spec.SetField(auditlog.FieldErrorCode, field.TypeInt32, value)
		_node.ErrorCode = &value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(auditlog.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = value
	}
	if value, ok := _c.mutation.LatencyMs(); ok {
		_spec.SetField(auditlog.FieldLatencyMs, field.TypeInt64, value)
		_node.LatencyMs = value
	}
	if value, ok := _c.mutation.PeerAddress(); ok {
		_spec.SetField(auditlog.FieldPeerAddress, field.TypeString, value)
		_node.PeerAddress = value
	}
	if value, ok := _c.mutation.GeoLocation(); ok {
		_spec.SetField(auditlog.FieldGeoLocation, field.TypeJSON, value)
		_node.GeoLocation = value
	}
	if value, ok := _c.mutation.LogHash(); ok {
		_spec.SetField(auditlog.FieldLogHash, field.TypeString, value)
		_node.LogHash = value
	}
	if value, ok := _c.mutation.Signature(); ok {
		_spec.SetField(auditlog.FieldSignature, field.TypeBytes, value)
		_node.Signature = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(auditlog.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	return _node, _spec
}

// AuditLogCreateBulk is the builder for creating many AuditLog entities in bulk.
type AuditLogCreateBulk struct {
	config
	err      error
	builders []*AuditLogCreate
}

// Save creates the AuditLog entities in the database.
func (_c *AuditLogCreateBulk) Save(ctx context.Context) ([]*AuditLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AuditLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuditLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint32(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AuditLogCreateBulk) SaveX(ctx context.Context) []*AuditLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuditLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuditLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
