// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/go-tangra/go-tangra-warden/internal/data/ent/folder"
	"github.com/go-tangra/go-tangra-warden/internal/data/ent/permission"
	"github.com/go-tangra/go-tangra-warden/internal/data/ent/secret"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FolderCreate is the builder for creating a Folder entity.
type FolderCreate struct {
	config
	mutation *FolderMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreateBy sets the "create_by" field.
func (_c *FolderCreate) SetCreateBy(v uint32) *FolderCreate {
	_c.mutation.SetCreateBy(v)
	return _c
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_c *FolderCreate) SetNillableCreateBy(v *uint32) *FolderCreate {
	if v != nil {
		_c.SetCreateBy(*v)
	}
	return _c
}

// SetCreateTime sets the "create_time" field.
func (_c *FolderCreate) SetCreateTime(v time.Time) *FolderCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *FolderCreate) SetNillableCreateTime(v *time.Time) *FolderCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *FolderCreate) SetUpdateTime(v time.Time) *FolderCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *FolderCreate) SetNillableUpdateTime(v *time.Time) *FolderCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetDeleteTime sets the "delete_time" field.
func (_c *FolderCreate) SetDeleteTime(v time.Time) *FolderCreate {
	_c.mutation.SetDeleteTime(v)
	return _c
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_c *FolderCreate) SetNillableDeleteTime(v *time.Time) *FolderCreate {
	if v != nil {
		_c.SetDeleteTime(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *FolderCreate) SetTenantID(v uint32) *FolderCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *FolderCreate) SetNillableTenantID(v *uint32) *FolderCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetParentID sets the "parent_id" field.
func (_c *FolderCreate) SetParentID(v string) *FolderCreate {
	_c.mutation.SetParentID(v)
	return _c
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_c *FolderCreate) SetNillableParentID(v *string) *FolderCreate {
	if v != nil {
		_c.SetParentID(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *FolderCreate) SetName(v string) *FolderCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetPath sets the "path" field.
func (_c *FolderCreate) SetPath(v string) *FolderCreate {
	_c.mutation.SetPath(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *FolderCreate) SetDescription(v string) *FolderCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *FolderCreate) SetNillableDescription(v *string) *FolderCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetDepth sets the "depth" field.
func (_c *FolderCreate) SetDepth(v int32) *FolderCreate {
	_c.mutation.SetDepth(v)
	return _c
}

// SetNillableDepth sets the "depth" field if the given value is not nil.
func (_c *FolderCreate) SetNillableDepth(v *int32) *FolderCreate {
	if v != nil {
		_c.SetDepth(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *FolderCreate) SetID(v string) *FolderCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetParent sets the "parent" edge to the Folder entity.
func (_c *FolderCreate) SetParent(v *Folder) *FolderCreate {
	return _c.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the Folder entity by IDs.
func (_c *FolderCreate) AddChildIDs(ids ...string) *FolderCreate {
	_c.mutation.AddChildIDs(ids...)
	return _c
}

// AddChildren adds the "children" edges to the Folder entity.
func (_c *FolderCreate) AddChildren(v ...*Folder) *FolderCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddChildIDs(ids...)
}

// AddSecretIDs adds the "secrets" edge to the Secret entity by IDs.
func (_c *FolderCreate) AddSecretIDs(ids ...string) *FolderCreate {
	_c.mutation.AddSecretIDs(ids...)
	return _c
}

// AddSecrets adds the "secrets" edges to the Secret entity.
func (_c *FolderCreate) AddSecrets(v ...*Secret) *FolderCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSecretIDs(ids...)
}

// AddPermissionIDs adds the "permissions" edge to the Permission entity by IDs.
func (_c *FolderCreate) AddPermissionIDs(ids ...int) *FolderCreate {
	_c.mutation.AddPermissionIDs(ids...)
	return _c
}

// AddPermissions adds the "permissions" edges to the Permission entity.
func (_c *FolderCreate) AddPermissions(v ...*Permission) *FolderCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPermissionIDs(ids...)
}

// Mutation returns the FolderMutation object of the builder.
func (_c *FolderCreate) Mutation() *FolderMutation {
	return _c.mutation
}

// Save creates the Folder in the database.
func (_c *FolderCreate) Save(ctx context.Context) (*Folder, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FolderCreate) SaveX(ctx context.Context) *Folder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FolderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FolderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *FolderCreate) defaults() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := folder.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.Depth(); !ok {
		v := folder.DefaultDepth
		_c.mutation.SetDepth(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *FolderCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Folder.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := folder.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Folder.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Path(); !ok {
		return &ValidationError{Name: "path", err: errors.New(`ent: missing required field "Folder.path"`)}
	}
	if v, ok := _c.mutation.Path(); ok {
		if err := folder.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "Folder.path": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Description(); ok {
		if err := folder.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Folder.description": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Depth(); !ok {
		return &ValidationError{Name: "depth", err: errors.New(`ent: missing required field "Folder.depth"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := folder.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Folder.id": %w`, err)}
		}
	}
	return nil
}

func (_c *FolderCreate) sqlSave(ctx context.Context) (*Folder, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Folder.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *FolderCreate) createSpec() (*Folder, *sqlgraph.CreateSpec) {
	var (
		_node = &Folder{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(folder.Table, sqlgraph.NewFieldSpec(folder.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreateBy(); ok {
		_spec.SetField(folder.FieldCreateBy, field.TypeUint32, value)
		_node.CreateBy = &value
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(folder.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = &value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(folder.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = &value
	}
	if value, ok := _c.mutation.DeleteTime(); ok {
		_spec.SetField(folder.FieldDeleteTime, field.TypeTime, value)
		_node.DeleteTime = &value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(folder.FieldTenantID, field.TypeUint32, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(folder.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Path(); ok {
		_spec.SetField(folder.FieldPath, field.TypeString, value)
		_node.Path = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(folder.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Depth(); ok {
		_spec.SetField(folder.FieldDepth, field.TypeInt32, value)
		_node.Depth = value
	}
	if nodes := _c.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   folder.ParentTable,
			Columns: []string{folder.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(folder.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ParentID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   folder.ChildrenTable,
			Columns: []string{folder.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(folder.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SecretsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   folder.SecretsTable,
			Columns: []string{folder.SecretsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(secret.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PermissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   folder.PermissionsTable,
			Columns: []string{folder.PermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(permission.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Folder.Create().
//		SetCreateBy(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.FolderUpsert) {
//			SetCreateBy(v+v).
//		}).
//		Exec(ctx)
func (_c *FolderCreate) OnConflict(opts ...sql.ConflictOption) *FolderUpsertOne {
	_c.conflict = opts
	return &FolderUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Folder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *FolderCreate) OnConflictColumns(columns ...string) *FolderUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &FolderUpsertOne{
		create: _c,
	}
}

type (
	// FolderUpsertOne is the builder for "upsert"-ing
	//  one Folder node.
	FolderUpsertOne struct {
		create *FolderCreate
	}

	// FolderUpsert is the "OnConflict" setter.
	FolderUpsert struct {
		*sql.UpdateSet
	}
)

// SetCreateBy sets the "create_by" field.
func (u *FolderUpsert) SetCreateBy(v uint32) *FolderUpsert {
	u.Set(folder.FieldCreateBy, v)
	return u
}

// UpdateCreateBy sets the "create_by" field to the value that was provided on create.
func (u *FolderUpsert) UpdateCreateBy() *FolderUpsert {
	u.SetExcluded(folder.FieldCreateBy)
	return u
}

// AddCreateBy adds v to the "create_by" field.
func (u *FolderUpsert) AddCreateBy(v uint32) *FolderUpsert {
	u.Add(folder.FieldCreateBy, v)
	return u
}

// ClearCreateBy clears the value of the "create_by" field.
func (u *FolderUpsert) ClearCreateBy() *FolderUpsert {
	u.SetNull(folder.FieldCreateBy)
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *FolderUpsert) SetUpdateTime(v time.Time) *FolderUpsert {
	u.Set(folder.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *FolderUpsert) UpdateUpdateTime() *FolderUpsert {
	u.SetExcluded(folder.FieldUpdateTime)
	return u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *FolderUpsert) ClearUpdateTime() *FolderUpsert {
	u.SetNull(folder.FieldUpdateTime)
	return u
}

// SetDeleteTime sets the "delete_time" field.
func (u *FolderUpsert) SetDeleteTime(v time.Time) *FolderUpsert {
	u.Set(folder.FieldDeleteTime, v)
	return u
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *FolderUpsert) UpdateDeleteTime() *FolderUpsert {
	u.SetExcluded(folder.FieldDeleteTime)
	return u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *FolderUpsert) ClearDeleteTime() *FolderUpsert {
	u.SetNull(folder.FieldDeleteTime)
	return u
}

// SetParentID sets the "parent_id" field.
func (u *FolderUpsert) SetParentID(v string) *FolderUpsert {
	u.Set(folder.FieldParentID, v)
	return u
}

// UpdateParentID sets the "parent_id" field to the value that was provided on create.
func (u *FolderUpsert) UpdateParentID() *FolderUpsert {
	u.SetExcluded(folder.FieldParentID)
	return u
}

// ClearParentID clears the value of the "parent_id" field.
func (u *FolderUpsert) ClearParentID() *FolderUpsert {
	u.SetNull(folder.FieldParentID)
	return u
}

// SetName sets the "name" field.
func (u *FolderUpsert) SetName(v string) *FolderUpsert {
	u.Set(folder.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *FolderUpsert) UpdateName() *FolderUpsert {
	u.SetExcluded(folder.FieldName)
	return u
}

// SetPath sets the "path" field.
func (u *FolderUpsert) SetPath(v string) *FolderUpsert {
	u.Set(folder.FieldPath, v)
	return u
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *FolderUpsert) UpdatePath() *FolderUpsert {
	u.SetExcluded(folder.FieldPath)
	return u
}

// SetDescription sets the "description" field.
func (u *FolderUpsert) SetDescription(v string) *FolderUpsert {
	u.Set(folder.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *FolderUpsert) UpdateDescription() *FolderUpsert {
	u.SetExcluded(folder.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *FolderUpsert) ClearDescription() *FolderUpsert {
	u.SetNull(folder.FieldDescription)
	return u
}

// SetDepth sets the "depth" field.
func (u *FolderUpsert) SetDepth(v int32) *FolderUpsert {
	u.Set(folder.FieldDepth, v)
	return u
}

// UpdateDepth sets the "depth" field to the value that was provided on create.
func (u *FolderUpsert) UpdateDepth() *FolderUpsert {
	u.SetExcluded(folder.FieldDepth)
	return u
}

// AddDepth adds v to the "depth" field.
func (u *FolderUpsert) AddDepth(v int32) *FolderUpsert {
	u.Add(folder.FieldDepth, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Folder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(folder.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *FolderUpsertOne) UpdateNewValues() *FolderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(folder.FieldID)
		}
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(folder.FieldCreateTime)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(folder.FieldTenantID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Folder.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *FolderUpsertOne) Ignore() *FolderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *FolderUpsertOne) DoNothing() *FolderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the FolderCreate.OnConflict
// documentation for more info.
func (u *FolderUpsertOne) Update(set func(*FolderUpsert)) *FolderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&FolderUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreateBy sets the "create_by" field.
func (u *FolderUpsertOne) SetCreateBy(v uint32) *FolderUpsertOne {
	return u.Update(func(s *FolderUpsert) {
		s.SetCreateBy(v)
	})
}

// AddCreateBy adds v to the "create_by" field.
func (u *FolderUpsertOne) AddCreateBy(v uint32) *FolderUpsertOne {
	return u.Update(func(s *FolderUpsert) {
		s.AddCreateBy(v)
	})
}

// UpdateCreateBy sets the "create_by" field to the value that was provided on create.
func (u *FolderUpsertOne) UpdateCreateBy() *FolderUpsertOne {
	return u.Update(func(s *FolderUpsert) {
		s.UpdateCreateBy()
	})
}

// ClearCreateBy clears the value of the "create_by" field.
func (u *FolderUpsertOne) ClearCreateBy() *FolderUpsertOne {
	return u.Update(func(s *FolderUpsert) {
		s.ClearCreateBy()
	})
}

// SetUpdateTime sets the "update_time" field.
func (u *FolderUpsertOne) SetUpdateTime(v time.Time) *FolderUpsertOne {
	return u.Update(func(s *FolderUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *FolderUpsertOne) UpdateUpdateTime() *FolderUpsertOne {
	return u.Update(func(s *FolderUpsert) {
		s.UpdateUpdateTime()
	})
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *FolderUpsertOne) ClearUpdateTime() *FolderUpsertOne {
	return u.Update(func(s *FolderUpsert) {
		s.ClearUpdateTime()
	})
}

// SetDeleteTime sets the "delete_time" field.
func (u *FolderUpsertOne) SetDeleteTime(v time.Time) *FolderUpsertOne {
	return u.Update(func(s *FolderUpsert) {
		s.SetDeleteTime(v)
	})
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *FolderUpsertOne) UpdateDeleteTime() *FolderUpsertOne {
	return u.Update(func(s *FolderUpsert) {
		s.UpdateDeleteTime()
	})
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *FolderUpsertOne) ClearDeleteTime() *FolderUpsertOne {
	return u.Update(func(s *FolderUpsert) {
		s.ClearDeleteTime()
	})
}

// SetParentID sets the "parent_id" field.
func (u *FolderUpsertOne) SetParentID(v string) *FolderUpsertOne {
	return u.Update(func(s *FolderUpsert) {
		s.SetParentID(v)
	})
}

// UpdateParentID sets the "parent_id" field to the value that was provided on create.
func (u *FolderUpsertOne) UpdateParentID() *FolderUpsertOne {
	return u.Update(func(s *FolderUpsert) {
		s.UpdateParentID()
	})
}

// ClearParentID clears the value of the "parent_id" field.
func (u *FolderUpsertOne) ClearParentID() *FolderUpsertOne {
	return u.Update(func(s *FolderUpsert) {
		s.ClearParentID()
	})
}

// SetName sets the "name" field.
func (u *FolderUpsertOne) SetName(v string) *FolderUpsertOne {
	return u.Update(func(s *FolderUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *FolderUpsertOne) UpdateName() *FolderUpsertOne {
	return u.Update(func(s *FolderUpsert) {
		s.UpdateName()
	})
}

// SetPath sets the "path" field.
func (u *FolderUpsertOne) SetPath(v string) *FolderUpsertOne {
	return u.Update(func(s *FolderUpsert) {
		s.SetPath(v)
	})
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *FolderUpsertOne) UpdatePath() *FolderUpsertOne {
	return u.Update(func(s *FolderUpsert) {
		s.UpdatePath()
	})
}

// SetDescription sets the "description" field.
func (u *FolderUpsertOne) SetDescription(v string) *FolderUpsertOne {
	return u.Update(func(s *FolderUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *FolderUpsertOne) UpdateDescription() *FolderUpsertOne {
	return u.Update(func(s *FolderUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *FolderUpsertOne) ClearDescription() *FolderUpsertOne {
	return u.Update(func(s *FolderUpsert) {
		s.ClearDescription()
	})
}

// SetDepth sets the "depth" field.
func (u *FolderUpsertOne) SetDepth(v int32) *FolderUpsertOne {
	return u.Update(func(s *FolderUpsert) {
		s.SetDepth(v)
	})
}

// AddDepth adds v to the "depth" field.
func (u *FolderUpsertOne) AddDepth(v int32) *FolderUpsertOne {
	return u.Update(func(s *FolderUpsert) {
		s.AddDepth(v)
	})
}

// UpdateDepth sets the "depth" field to the value that was provided on create.
func (u *FolderUpsertOne) UpdateDepth() *FolderUpsertOne {
	return u.Update(func(s *FolderUpsert) {
		s.UpdateDepth()
	})
}

// Exec executes the query.
func (u *FolderUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for FolderCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *FolderUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *FolderUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: FolderUpsertOne.ID is not supported by MySQL driver. Use FolderUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *FolderUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// FolderCreateBulk is the builder for creating many Folder entities in bulk.
type FolderCreateBulk struct {
	config
	err      error
	builders []*FolderCreate
	conflict []sql.ConflictOption
}

// Save creates the Folder entities in the database.
func (_c *FolderCreateBulk) Save(ctx context.Context) ([]*Folder, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Folder, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FolderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FolderCreateBulk) SaveX(ctx context.Context) []*Folder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FolderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FolderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Folder.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.FolderUpsert) {
//			SetCreateBy(v+v).
//		}).
//		Exec(ctx)
func (_c *FolderCreateBulk) OnConflict(opts ...sql.ConflictOption) *FolderUpsertBulk {
	_c.conflict = opts
	return &FolderUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Folder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *FolderCreateBulk) OnConflictColumns(columns ...string) *FolderUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &FolderUpsertBulk{
		create: _c,
	}
}

// FolderUpsertBulk is the builder for "upsert"-ing
// a bulk of Folder nodes.
type FolderUpsertBulk struct {
	create *FolderCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Folder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(folder.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *FolderUpsertBulk) UpdateNewValues() *FolderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(folder.FieldID)
			}
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(folder.FieldCreateTime)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(folder.FieldTenantID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Folder.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *FolderUpsertBulk) Ignore() *FolderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *FolderUpsertBulk) DoNothing() *FolderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the FolderCreateBulk.OnConflict
// documentation for more info.
func (u *FolderUpsertBulk) Update(set func(*FolderUpsert)) *FolderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&FolderUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreateBy sets the "create_by" field.
func (u *FolderUpsertBulk) SetCreateBy(v uint32) *FolderUpsertBulk {
	return u.Update(func(s *FolderUpsert) {
		s.SetCreateBy(v)
	})
}

// AddCreateBy adds v to the "create_by" field.
func (u *FolderUpsertBulk) AddCreateBy(v uint32) *FolderUpsertBulk {
	return u.Update(func(s *FolderUpsert) {
		s.AddCreateBy(v)
	})
}

// UpdateCreateBy sets the "create_by" field to the value that was provided on create.
func (u *FolderUpsertBulk) UpdateCreateBy() *FolderUpsertBulk {
	return u.Update(func(s *FolderUpsert) {
		s.UpdateCreateBy()
	})
}

// ClearCreateBy clears the value of the "create_by" field.
func (u *FolderUpsertBulk) ClearCreateBy() *FolderUpsertBulk {
	return u.Update(func(s *FolderUpsert) {
		s.ClearCreateBy()
	})
}

// SetUpdateTime sets the "update_time" field.
func (u *FolderUpsertBulk) SetUpdateTime(v time.Time) *FolderUpsertBulk {
	return u.Update(func(s *FolderUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *FolderUpsertBulk) UpdateUpdateTime() *FolderUpsertBulk {
	return u.Update(func(s *FolderUpsert) {
		s.UpdateUpdateTime()
	})
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *FolderUpsertBulk) ClearUpdateTime() *FolderUpsertBulk {
	return u.Update(func(s *FolderUpsert) {
		s.ClearUpdateTime()
	})
}

// SetDeleteTime sets the "delete_time" field.
func (u *FolderUpsertBulk) SetDeleteTime(v time.Time) *FolderUpsertBulk {
	return u.Update(func(s *FolderUpsert) {
		s.SetDeleteTime(v)
	})
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *FolderUpsertBulk) UpdateDeleteTime() *FolderUpsertBulk {
	return u.Update(func(s *FolderUpsert) {
		s.UpdateDeleteTime()
	})
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *FolderUpsertBulk) ClearDeleteTime() *FolderUpsertBulk {
	return u.Update(func(s *FolderUpsert) {
		s.ClearDeleteTime()
	})
}

// SetParentID sets the "parent_id" field.
func (u *FolderUpsertBulk) SetParentID(v string) *FolderUpsertBulk {
	return u.Update(func(s *FolderUpsert) {
		s.SetParentID(v)
	})
}

// UpdateParentID sets the "parent_id" field to the value that was provided on create.
func (u *FolderUpsertBulk) UpdateParentID() *FolderUpsertBulk {
	return u.Update(func(s *FolderUpsert) {
		s.UpdateParentID()
	})
}

// ClearParentID clears the value of the "parent_id" field.
func (u *FolderUpsertBulk) ClearParentID() *FolderUpsertBulk {
	return u.Update(func(s *FolderUpsert) {
		s.ClearParentID()
	})
}

// SetName sets the "name" field.
func (u *FolderUpsertBulk) SetName(v string) *FolderUpsertBulk {
	return u.Update(func(s *FolderUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *FolderUpsertBulk) UpdateName() *FolderUpsertBulk {
	return u.Update(func(s *FolderUpsert) {
		s.UpdateName()
	})
}

// SetPath sets the "path" field.
func (u *FolderUpsertBulk) SetPath(v string) *FolderUpsertBulk {
	return u.Update(func(s *FolderUpsert) {
		s.SetPath(v)
	})
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *FolderUpsertBulk) UpdatePath() *FolderUpsertBulk {
	return u.Update(func(s *FolderUpsert) {
		s.UpdatePath()
	})
}

// SetDescription sets the "description" field.
func (u *FolderUpsertBulk) SetDescription(v string) *FolderUpsertBulk {
	return u.Update(func(s *FolderUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *FolderUpsertBulk) UpdateDescription() *FolderUpsertBulk {
	return u.Update(func(s *FolderUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *FolderUpsertBulk) ClearDescription() *FolderUpsertBulk {
	return u.Update(func(s *FolderUpsert) {
		s.ClearDescription()
	})
}

// SetDepth sets the "depth" field.
func (u *FolderUpsertBulk) SetDepth(v int32) *FolderUpsertBulk {
	return u.Update(func(s *FolderUpsert) {
		s.SetDepth(v)
	})
}

// AddDepth adds v to the "depth" field.
func (u *FolderUpsertBulk) AddDepth(v int32) *FolderUpsertBulk {
	return u.Update(func(s *FolderUpsert) {
		s.AddDepth(v)
	})
}

// UpdateDepth sets the "depth" field to the value that was provided on create.
func (u *FolderUpsertBulk) UpdateDepth() *FolderUpsertBulk {
	return u.Update(func(s *FolderUpsert) {
		s.UpdateDepth()
	})
}

// Exec executes the query.
func (u *FolderUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the FolderCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for FolderCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *FolderUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
