// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"github.com/go-tangra/go-tangra-warden/internal/data/ent/secret"
	"github.com/go-tangra/go-tangra-warden/internal/data/ent/secretversion"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// SecretVersion is the model entity for the SecretVersion schema.
type SecretVersion struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 创建者ID
	CreateBy *uint32 `json:"create_by,omitempty"`
	// 创建时间
	CreateTime *time.Time `json:"create_time,omitempty"`
	// 更新时间
	UpdateTime *time.Time `json:"update_time,omitempty"`
	// 删除时间
	DeleteTime *time.Time `json:"delete_time,omitempty"`
	// Parent secret ID
	SecretID string `json:"secret_id,omitempty"`
	// Version number (1, 2, 3...)
	VersionNumber int32 `json:"version_number,omitempty"`
	// Vault path for this version
	VaultPath string `json:"vault_path,omitempty"`
	// Version comment describing the change
	Comment string `json:"comment,omitempty"`
	// SHA-256 checksum of the password
	Checksum string `json:"checksum,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SecretVersionQuery when eager-loading is set.
	Edges        SecretVersionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SecretVersionEdges holds the relations/edges for other nodes in the graph.
type SecretVersionEdges struct {
	// Parent secret
	Secret *Secret `json:"secret,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SecretOrErr returns the Secret value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SecretVersionEdges) SecretOrErr() (*Secret, error) {
	if e.Secret != nil {
		return e.Secret, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: secret.Label}
	}
	return nil, &NotLoadedError{edge: "secret"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SecretVersion) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case secretversion.FieldID, secretversion.FieldCreateBy, secretversion.FieldVersionNumber:
			values[i] = new(sql.NullInt64)
		case secretversion.FieldSecretID, secretversion.FieldVaultPath, secretversion.FieldComment, secretversion.FieldChecksum:
			values[i] = new(sql.NullString)
		case secretversion.FieldCreateTime, secretversion.FieldUpdateTime, secretversion.FieldDeleteTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SecretVersion fields.
func (_m *SecretVersion) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case secretversion.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case secretversion.FieldCreateBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field create_by", values[i])
			} else if value.Valid {
				_m.CreateBy = new(uint32)
				*_m.CreateBy = uint32(value.Int64)
			}
		case secretversion.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = new(time.Time)
				*_m.CreateTime = value.Time
			}
		case secretversion.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = new(time.Time)
				*_m.UpdateTime = value.Time
			}
		case secretversion.FieldDeleteTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field delete_time", values[i])
			} else if value.Valid {
				_m.DeleteTime = new(time.Time)
				*_m.DeleteTime = value.Time
			}
		case secretversion.FieldSecretID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field secret_id", values[i])
			} else if value.Valid {
				_m.SecretID = value.String
			}
		case secretversion.FieldVersionNumber:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version_number", values[i])
			} else if value.Valid {
				_m.VersionNumber = int32(value.Int64)
			}
		case secretversion.FieldVaultPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field vault_path", values[i])
			} else if value.Valid {
				_m.VaultPath = value.String
			}
		case secretversion.FieldComment:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field comment", values[i])
			} else if value.Valid {
				_m.Comment = value.String
			}
		case secretversion.FieldChecksum:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field checksum", values[i])
			} else if value.Valid {
				_m.Checksum = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SecretVersion.
// This includes values selected through modifiers, order, etc.
func (_m *SecretVersion) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySecret queries the "secret" edge of the SecretVersion entity.
func (_m *SecretVersion) QuerySecret() *SecretQuery {
	return NewSecretVersionClient(_m.config).QuerySecret(_m)
}

// Update returns a builder for updating this SecretVersion.
// Note that you need to call SecretVersion.Unwrap() before calling this method if this SecretVersion
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SecretVersion) Update() *SecretVersionUpdateOne {
	return NewSecretVersionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SecretVersion entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SecretVersion) Unwrap() *SecretVersion {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SecretVersion is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SecretVersion) String() string {
	var builder strings.Builder
	builder.WriteString("SecretVersion(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.CreateBy; v != nil {
		builder.WriteString("create_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CreateTime; v != nil {
		builder.WriteString("create_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdateTime; v != nil {
		builder.WriteString("update_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DeleteTime; v != nil {
		builder.WriteString("delete_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("secret_id=")
	builder.WriteString(_m.SecretID)
	builder.WriteString(", ")
	builder.WriteString("version_number=")
	builder.WriteString(fmt.Sprintf("%v", _m.VersionNumber))
	builder.WriteString(", ")
	builder.WriteString("vault_path=")
	builder.WriteString(_m.VaultPath)
	builder.WriteString(", ")
	builder.WriteString("comment=")
	builder.WriteString(_m.Comment)
	builder.WriteString(", ")
	builder.WriteString("checksum=")
	builder.WriteString(_m.Checksum)
	builder.WriteByte(')')
	return builder.String()
}

// SecretVersions is a parsable slice of SecretVersion.
type SecretVersions []*SecretVersion
