// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/go-tangra/go-tangra-warden/internal/data/ent/secret"
	"github.com/go-tangra/go-tangra-warden/internal/data/ent/secretversion"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SecretVersionCreate is the builder for creating a SecretVersion entity.
type SecretVersionCreate struct {
	config
	mutation *SecretVersionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreateBy sets the "create_by" field.
func (_c *SecretVersionCreate) SetCreateBy(v uint32) *SecretVersionCreate {
	_c.mutation.SetCreateBy(v)
	return _c
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_c *SecretVersionCreate) SetNillableCreateBy(v *uint32) *SecretVersionCreate {
	if v != nil {
		_c.SetCreateBy(*v)
	}
	return _c
}

// SetCreateTime sets the "create_time" field.
func (_c *SecretVersionCreate) SetCreateTime(v time.Time) *SecretVersionCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *SecretVersionCreate) SetNillableCreateTime(v *time.Time) *SecretVersionCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *SecretVersionCreate) SetUpdateTime(v time.Time) *SecretVersionCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *SecretVersionCreate) SetNillableUpdateTime(v *time.Time) *SecretVersionCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetDeleteTime sets the "delete_time" field.
func (_c *SecretVersionCreate) SetDeleteTime(v time.Time) *SecretVersionCreate {
	_c.mutation.SetDeleteTime(v)
	return _c
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_c *SecretVersionCreate) SetNillableDeleteTime(v *time.Time) *SecretVersionCreate {
	if v != nil {
		_c.SetDeleteTime(*v)
	}
	return _c
}

// SetSecretID sets the "secret_id" field.
func (_c *SecretVersionCreate) SetSecretID(v string) *SecretVersionCreate {
	_c.mutation.SetSecretID(v)
	return _c
}

// SetVersionNumber sets the "version_number" field.
func (_c *SecretVersionCreate) SetVersionNumber(v int32) *SecretVersionCreate {
	_c.mutation.SetVersionNumber(v)
	return _c
}

// SetVaultPath sets the "vault_path" field.
func (_c *SecretVersionCreate) SetVaultPath(v string) *SecretVersionCreate {
	_c.mutation.SetVaultPath(v)
	return _c
}

// SetComment sets the "comment" field.
func (_c *SecretVersionCreate) SetComment(v string) *SecretVersionCreate {
	_c.mutation.SetComment(v)
	return _c
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (_c *SecretVersionCreate) SetNillableComment(v *string) *SecretVersionCreate {
	if v != nil {
		_c.SetComment(*v)
	}
	return _c
}

// SetChecksum sets the "checksum" field.
func (_c *SecretVersionCreate) SetChecksum(v string) *SecretVersionCreate {
	_c.mutation.SetChecksum(v)
	return _c
}

// SetSecret sets the "secret" edge to the Secret entity.
func (_c *SecretVersionCreate) SetSecret(v *Secret) *SecretVersionCreate {
	return _c.SetSecretID(v.ID)
}

// Mutation returns the SecretVersionMutation object of the builder.
func (_c *SecretVersionCreate) Mutation() *SecretVersionMutation {
	return _c.mutation
}

// Save creates the SecretVersion in the database.
func (_c *SecretVersionCreate) Save(ctx context.Context) (*SecretVersion, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SecretVersionCreate) SaveX(ctx context.Context) *SecretVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SecretVersionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SecretVersionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SecretVersionCreate) check() error {
	if _, ok := _c.mutation.SecretID(); !ok {
		return &ValidationError{Name: "secret_id", err: errors.New(`ent: missing required field "SecretVersion.secret_id"`)}
	}
	if v, ok := _c.mutation.SecretID(); ok {
		if err := secretversion.SecretIDValidator(v); err != nil {
			return &ValidationError{Name: "secret_id", err: fmt.Errorf(`ent: validator failed for field "SecretVersion.secret_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.VersionNumber(); !ok {
		return &ValidationError{Name: "version_number", err: errors.New(`ent: missing required field "SecretVersion.version_number"`)}
	}
	if v, ok := _c.mutation.VersionNumber(); ok {
		if err := secretversion.VersionNumberValidator(v); err != nil {
			return &ValidationError{Name: "version_number", err: fmt.Errorf(`ent: validator failed for field "SecretVersion.version_number": %w`, err)}
		}
	}
	if _, ok := _c.mutation.VaultPath(); !ok {
		return &ValidationError{Name: "vault_path", err: errors.New(`ent: missing required field "SecretVersion.vault_path"`)}
	}
	if v, ok := _c.mutation.VaultPath(); ok {
		if err := secretversion.VaultPathValidator(v); err != nil {
			return &ValidationError{Name: "vault_path", err: fmt.Errorf(`ent: validator failed for field "SecretVersion.vault_path": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Comment(); ok {
		if err := secretversion.CommentValidator(v); err != nil {
			return &ValidationError{Name: "comment", err: fmt.Errorf(`ent: validator failed for field "SecretVersion.comment": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Checksum(); !ok {
		return &ValidationError{Name: "checksum", err: errors.New(`ent: missing required field "SecretVersion.checksum"`)}
	}
	if v, ok := _c.mutation.Checksum(); ok {
		if err := secretversion.ChecksumValidator(v); err != nil {
			return &ValidationError{Name: "checksum", err: fmt.Errorf(`ent: validator failed for field "SecretVersion.checksum": %w`, err)}
		}
	}
	if len(_c.mutation.SecretIDs()) == 0 {
		return &ValidationError{Name: "secret", err: errors.New(`ent: missing required edge "SecretVersion.secret"`)}
	}
	return nil
}

func (_c *SecretVersionCreate) sqlSave(ctx context.Context) (*SecretVersion, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SecretVersionCreate) createSpec() (*SecretVersion, *sqlgraph.CreateSpec) {
	var (
		_node = &SecretVersion{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(secretversion.Table, sqlgraph.NewFieldSpec(secretversion.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreateBy(); ok {
		_spec.SetField(secretversion.FieldCreateBy, field.TypeUint32, value)
		_node.CreateBy = &value
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(secretversion.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = &value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(secretversion.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = &value
	}
	if value, ok := _c.mutation.DeleteTime(); ok {
		_spec.SetField(secretversion.FieldDeleteTime, field.TypeTime, value)
		_node.DeleteTime = &value
	}
	if value, ok := _c.mutation.VersionNumber(); ok {
		_spec.SetField(secretversion.FieldVersionNumber, field.TypeInt32, value)
		_node.VersionNumber = value
	}
	if value, ok := _c.mutation.VaultPath(); ok {
		_spec.SetField(secretversion.FieldVaultPath, field.TypeString, value)
		_node.VaultPath = value
	}
	if value, ok := _c.mutation.Comment(); ok {
		_spec.SetField(secretversion.FieldComment, field.TypeString, value)
		_node.Comment = value
	}
	if value, ok := _c.mutation.Checksum(); ok {
		_spec.SetField(secretversion.FieldChecksum, field.TypeString, value)
		_node.Checksum = value
	}
	if nodes := _c.mutation.SecretIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   secretversion.SecretTable,
			Columns: []string{secretversion.SecretColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(secret.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SecretID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SecretVersion.Create().
//		SetCreateBy(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SecretVersionUpsert) {
//			SetCreateBy(v+v).
//		}).
//		Exec(ctx)
func (_c *SecretVersionCreate) OnConflict(opts ...sql.ConflictOption) *SecretVersionUpsertOne {
	_c.conflict = opts
	return &SecretVersionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SecretVersion.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SecretVersionCreate) OnConflictColumns(columns ...string) *SecretVersionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SecretVersionUpsertOne{
		create: _c,
	}
}

type (
	// SecretVersionUpsertOne is the builder for "upsert"-ing
	//  one SecretVersion node.
	SecretVersionUpsertOne struct {
		create *SecretVersionCreate
	}

	// SecretVersionUpsert is the "OnConflict" setter.
	SecretVersionUpsert struct {
		*sql.UpdateSet
	}
)

// SetCreateBy sets the "create_by" field.
func (u *SecretVersionUpsert) SetCreateBy(v uint32) *SecretVersionUpsert {
	u.Set(secretversion.FieldCreateBy, v)
	return u
}

// UpdateCreateBy sets the "create_by" field to the value that was provided on create.
func (u *SecretVersionUpsert) UpdateCreateBy() *SecretVersionUpsert {
	u.SetExcluded(secretversion.FieldCreateBy)
	return u
}

// AddCreateBy adds v to the "create_by" field.
func (u *SecretVersionUpsert) AddCreateBy(v uint32) *SecretVersionUpsert {
	u.Add(secretversion.FieldCreateBy, v)
	return u
}

// ClearCreateBy clears the value of the "create_by" field.
func (u *SecretVersionUpsert) ClearCreateBy() *SecretVersionUpsert {
	u.SetNull(secretversion.FieldCreateBy)
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *SecretVersionUpsert) SetUpdateTime(v time.Time) *SecretVersionUpsert {
	u.Set(secretversion.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *SecretVersionUpsert) UpdateUpdateTime() *SecretVersionUpsert {
	u.SetExcluded(secretversion.FieldUpdateTime)
	return u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *SecretVersionUpsert) ClearUpdateTime() *SecretVersionUpsert {
	u.SetNull(secretversion.FieldUpdateTime)
	return u
}

// SetDeleteTime sets the "delete_time" field.
func (u *SecretVersionUpsert) SetDeleteTime(v time.Time) *SecretVersionUpsert {
	u.Set(secretversion.FieldDeleteTime, v)
	return u
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *SecretVersionUpsert) UpdateDeleteTime() *SecretVersionUpsert {
	u.SetExcluded(secretversion.FieldDeleteTime)
	return u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *SecretVersionUpsert) ClearDeleteTime() *SecretVersionUpsert {
	u.SetNull(secretversion.FieldDeleteTime)
	return u
}

// SetSecretID sets the "secret_id" field.
func (u *SecretVersionUpsert) SetSecretID(v string) *SecretVersionUpsert {
	u.Set(secretversion.FieldSecretID, v)
	return u
}

// UpdateSecretID sets the "secret_id" field to the value that was provided on create.
func (u *SecretVersionUpsert) UpdateSecretID() *SecretVersionUpsert {
	u.SetExcluded(secretversion.FieldSecretID)
	return u
}

// SetVersionNumber sets the "version_number" field.
func (u *SecretVersionUpsert) SetVersionNumber(v int32) *SecretVersionUpsert {
	u.Set(secretversion.FieldVersionNumber, v)
	return u
}

// UpdateVersionNumber sets the "version_number" field to the value that was provided on create.
func (u *SecretVersionUpsert) UpdateVersionNumber() *SecretVersionUpsert {
	u.SetExcluded(secretversion.FieldVersionNumber)
	return u
}

// AddVersionNumber adds v to the "version_number" field.
func (u *SecretVersionUpsert) AddVersionNumber(v int32) *SecretVersionUpsert {
	u.Add(secretversion.FieldVersionNumber, v)
	return u
}

// SetVaultPath sets the "vault_path" field.
func (u *SecretVersionUpsert) SetVaultPath(v string) *SecretVersionUpsert {
	u.Set(secretversion.FieldVaultPath, v)
	return u
}

// UpdateVaultPath sets the "vault_path" field to the value that was provided on create.
func (u *SecretVersionUpsert) UpdateVaultPath() *SecretVersionUpsert {
	u.SetExcluded(secretversion.FieldVaultPath)
	return u
}

// SetComment sets the "comment" field.
func (u *SecretVersionUpsert) SetComment(v string) *SecretVersionUpsert {
	u.Set(secretversion.FieldComment, v)
	return u
}

// UpdateComment sets the "comment" field to the value that was provided on create.
func (u *SecretVersionUpsert) UpdateComment() *SecretVersionUpsert {
	u.SetExcluded(secretversion.FieldComment)
	return u
}

// ClearComment clears the value of the "comment" field.
func (u *SecretVersionUpsert) ClearComment() *SecretVersionUpsert {
	u.SetNull(secretversion.FieldComment)
	return u
}

// SetChecksum sets the "checksum" field.
func (u *SecretVersionUpsert) SetChecksum(v string) *SecretVersionUpsert {
	u.Set(secretversion.FieldChecksum, v)
	return u
}

// UpdateChecksum sets the "checksum" field to the value that was provided on create.
func (u *SecretVersionUpsert) UpdateChecksum() *SecretVersionUpsert {
	u.SetExcluded(secretversion.FieldChecksum)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SecretVersion.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SecretVersionUpsertOne) UpdateNewValues() *SecretVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(secretversion.FieldCreateTime)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SecretVersion.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SecretVersionUpsertOne) Ignore() *SecretVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SecretVersionUpsertOne) DoNothing() *SecretVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SecretVersionCreate.OnConflict
// documentation for more info.
func (u *SecretVersionUpsertOne) Update(set func(*SecretVersionUpsert)) *SecretVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SecretVersionUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreateBy sets the "create_by" field.
func (u *SecretVersionUpsertOne) SetCreateBy(v uint32) *SecretVersionUpsertOne {
	return u.Update(func(s *SecretVersionUpsert) {
		s.SetCreateBy(v)
	})
}

// AddCreateBy adds v to the "create_by" field.
func (u *SecretVersionUpsertOne) AddCreateBy(v uint32) *SecretVersionUpsertOne {
	return u.Update(func(s *SecretVersionUpsert) {
		s.AddCreateBy(v)
	})
}

// UpdateCreateBy sets the "create_by" field to the value that was provided on create.
func (u *SecretVersionUpsertOne) UpdateCreateBy() *SecretVersionUpsertOne {
	return u.Update(func(s *SecretVersionUpsert) {
		s.UpdateCreateBy()
	})
}

// ClearCreateBy clears the value of the "create_by" field.
func (u *SecretVersionUpsertOne) ClearCreateBy() *SecretVersionUpsertOne {
	return u.Update(func(s *SecretVersionUpsert) {
		s.ClearCreateBy()
	})
}

// SetUpdateTime sets the "update_time" field.
func (u *SecretVersionUpsertOne) SetUpdateTime(v time.Time) *SecretVersionUpsertOne {
	return u.Update(func(s *SecretVersionUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *SecretVersionUpsertOne) UpdateUpdateTime() *SecretVersionUpsertOne {
	return u.Update(func(s *SecretVersionUpsert) {
		s.UpdateUpdateTime()
	})
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *SecretVersionUpsertOne) ClearUpdateTime() *SecretVersionUpsertOne {
	return u.Update(func(s *SecretVersionUpsert) {
		s.ClearUpdateTime()
	})
}

// SetDeleteTime sets the "delete_time" field.
func (u *SecretVersionUpsertOne) SetDeleteTime(v time.Time) *SecretVersionUpsertOne {
	return u.Update(func(s *SecretVersionUpsert) {
		s.SetDeleteTime(v)
	})
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *SecretVersionUpsertOne) UpdateDeleteTime() *SecretVersionUpsertOne {
	return u.Update(func(s *SecretVersionUpsert) {
		s.UpdateDeleteTime()
	})
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *SecretVersionUpsertOne) ClearDeleteTime() *SecretVersionUpsertOne {
	return u.Update(func(s *SecretVersionUpsert) {
		s.ClearDeleteTime()
	})
}

// SetSecretID sets the "secret_id" field.
func (u *SecretVersionUpsertOne) SetSecretID(v string) *SecretVersionUpsertOne {
	return u.Update(func(s *SecretVersionUpsert) {
		s.SetSecretID(v)
	})
}

// UpdateSecretID sets the "secret_id" field to the value that was provided on create.
func (u *SecretVersionUpsertOne) UpdateSecretID() *SecretVersionUpsertOne {
	return u.Update(func(s *SecretVersionUpsert) {
		s.UpdateSecretID()
	})
}

// SetVersionNumber sets the "version_number" field.
func (u *SecretVersionUpsertOne) SetVersionNumber(v int32) *SecretVersionUpsertOne {
	return u.Update(func(s *SecretVersionUpsert) {
		s.SetVersionNumber(v)
	})
}

// AddVersionNumber adds v to the "version_number" field.
func (u *SecretVersionUpsertOne) AddVersionNumber(v int32) *SecretVersionUpsertOne {
	return u.Update(func(s *SecretVersionUpsert) {
		s.AddVersionNumber(v)
	})
}

// UpdateVersionNumber sets the "version_number" field to the value that was provided on create.
func (u *SecretVersionUpsertOne) UpdateVersionNumber() *SecretVersionUpsertOne {
	return u.Update(func(s *SecretVersionUpsert) {
		s.UpdateVersionNumber()
	})
}

// SetVaultPath sets the "vault_path" field.
func (u *SecretVersionUpsertOne) SetVaultPath(v string) *SecretVersionUpsertOne {
	return u.Update(func(s *SecretVersionUpsert) {
		s.SetVaultPath(v)
	})
}

// UpdateVaultPath sets the "vault_path" field to the value that was provided on create.
func (u *SecretVersionUpsertOne) UpdateVaultPath() *SecretVersionUpsertOne {
	return u.Update(func(s *SecretVersionUpsert) {
		s.UpdateVaultPath()
	})
}

// SetComment sets the "comment" field.
func (u *SecretVersionUpsertOne) SetComment(v string) *SecretVersionUpsertOne {
	return u.Update(func(s *SecretVersionUpsert) {
		s.SetComment(v)
	})
}

// UpdateComment sets the "comment" field to the value that was provided on create.
func (u *SecretVersionUpsertOne) UpdateComment() *SecretVersionUpsertOne {
	return u.Update(func(s *SecretVersionUpsert) {
		s.UpdateComment()
	})
}

// ClearComment clears the value of the "comment" field.
func (u *SecretVersionUpsertOne) ClearComment() *SecretVersionUpsertOne {
	return u.Update(func(s *SecretVersionUpsert) {
		s.ClearComment()
	})
}

// SetChecksum sets the "checksum" field.
func (u *SecretVersionUpsertOne) SetChecksum(v string) *SecretVersionUpsertOne {
	return u.Update(func(s *SecretVersionUpsert) {
		s.SetChecksum(v)
	})
}

// UpdateChecksum sets the "checksum" field to the value that was provided on create.
func (u *SecretVersionUpsertOne) UpdateChecksum() *SecretVersionUpsertOne {
	return u.Update(func(s *SecretVersionUpsert) {
		s.UpdateChecksum()
	})
}

// Exec executes the query.
func (u *SecretVersionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SecretVersionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SecretVersionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SecretVersionUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SecretVersionUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SecretVersionCreateBulk is the builder for creating many SecretVersion entities in bulk.
type SecretVersionCreateBulk struct {
	config
	err      error
	builders []*SecretVersionCreate
	conflict []sql.ConflictOption
}

// Save creates the SecretVersion entities in the database.
func (_c *SecretVersionCreateBulk) Save(ctx context.Context) ([]*SecretVersion, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SecretVersion, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SecretVersionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SecretVersionCreateBulk) SaveX(ctx context.Context) []*SecretVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SecretVersionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SecretVersionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SecretVersion.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SecretVersionUpsert) {
//			SetCreateBy(v+v).
//		}).
//		Exec(ctx)
func (_c *SecretVersionCreateBulk) OnConflict(opts ...sql.ConflictOption) *SecretVersionUpsertBulk {
	_c.conflict = opts
	return &SecretVersionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SecretVersion.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SecretVersionCreateBulk) OnConflictColumns(columns ...string) *SecretVersionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SecretVersionUpsertBulk{
		create: _c,
	}
}

// SecretVersionUpsertBulk is the builder for "upsert"-ing
// a bulk of SecretVersion nodes.
type SecretVersionUpsertBulk struct {
	create *SecretVersionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SecretVersion.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SecretVersionUpsertBulk) UpdateNewValues() *SecretVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(secretversion.FieldCreateTime)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SecretVersion.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SecretVersionUpsertBulk) Ignore() *SecretVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SecretVersionUpsertBulk) DoNothing() *SecretVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SecretVersionCreateBulk.OnConflict
// documentation for more info.
func (u *SecretVersionUpsertBulk) Update(set func(*SecretVersionUpsert)) *SecretVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SecretVersionUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreateBy sets the "create_by" field.
func (u *SecretVersionUpsertBulk) SetCreateBy(v uint32) *SecretVersionUpsertBulk {
	return u.Update(func(s *SecretVersionUpsert) {
		s.SetCreateBy(v)
	})
}

// AddCreateBy adds v to the "create_by" field.
func (u *SecretVersionUpsertBulk) AddCreateBy(v uint32) *SecretVersionUpsertBulk {
	return u.Update(func(s *SecretVersionUpsert) {
		s.AddCreateBy(v)
	})
}

// UpdateCreateBy sets the "create_by" field to the value that was provided on create.
func (u *SecretVersionUpsertBulk) UpdateCreateBy() *SecretVersionUpsertBulk {
	return u.Update(func(s *SecretVersionUpsert) {
		s.UpdateCreateBy()
	})
}

// ClearCreateBy clears the value of the "create_by" field.
func (u *SecretVersionUpsertBulk) ClearCreateBy() *SecretVersionUpsertBulk {
	return u.Update(func(s *SecretVersionUpsert) {
		s.ClearCreateBy()
	})
}

// SetUpdateTime sets the "update_time" field.
func (u *SecretVersionUpsertBulk) SetUpdateTime(v time.Time) *SecretVersionUpsertBulk {
	return u.Update(func(s *SecretVersionUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *SecretVersionUpsertBulk) UpdateUpdateTime() *SecretVersionUpsertBulk {
	return u.Update(func(s *SecretVersionUpsert) {
		s.UpdateUpdateTime()
	})
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *SecretVersionUpsertBulk) ClearUpdateTime() *SecretVersionUpsertBulk {
	return u.Update(func(s *SecretVersionUpsert) {
		s.ClearUpdateTime()
	})
}

// SetDeleteTime sets the "delete_time" field.
func (u *SecretVersionUpsertBulk) SetDeleteTime(v time.Time) *SecretVersionUpsertBulk {
	return u.Update(func(s *SecretVersionUpsert) {
		s.SetDeleteTime(v)
	})
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *SecretVersionUpsertBulk) UpdateDeleteTime() *SecretVersionUpsertBulk {
	return u.Update(func(s *SecretVersionUpsert) {
		s.UpdateDeleteTime()
	})
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *SecretVersionUpsertBulk) ClearDeleteTime() *SecretVersionUpsertBulk {
	return u.Update(func(s *SecretVersionUpsert) {
		s.ClearDeleteTime()
	})
}

// SetSecretID sets the "secret_id" field.
func (u *SecretVersionUpsertBulk) SetSecretID(v string) *SecretVersionUpsertBulk {
	return u.Update(func(s *SecretVersionUpsert) {
		s.SetSecretID(v)
	})
}

// UpdateSecretID sets the "secret_id" field to the value that was provided on create.
func (u *SecretVersionUpsertBulk) UpdateSecretID() *SecretVersionUpsertBulk {
	return u.Update(func(s *SecretVersionUpsert) {
		s.UpdateSecretID()
	})
}

// SetVersionNumber sets the "version_number" field.
func (u *SecretVersionUpsertBulk) SetVersionNumber(v int32) *SecretVersionUpsertBulk {
	return u.Update(func(s *SecretVersionUpsert) {
		s.SetVersionNumber(v)
	})
}

// AddVersionNumber adds v to the "version_number" field.
func (u *SecretVersionUpsertBulk) AddVersionNumber(v int32) *SecretVersionUpsertBulk {
	return u.Update(func(s *SecretVersionUpsert) {
		s.AddVersionNumber(v)
	})
}

// UpdateVersionNumber sets the "version_number" field to the value that was provided on create.
func (u *SecretVersionUpsertBulk) UpdateVersionNumber() *SecretVersionUpsertBulk {
	return u.Update(func(s *SecretVersionUpsert) {
		s.UpdateVersionNumber()
	})
}

// SetVaultPath sets the "vault_path" field.
func (u *SecretVersionUpsertBulk) SetVaultPath(v string) *SecretVersionUpsertBulk {
	return u.Update(func(s *SecretVersionUpsert) {
		s.SetVaultPath(v)
	})
}

// UpdateVaultPath sets the "vault_path" field to the value that was provided on create.
func (u *SecretVersionUpsertBulk) UpdateVaultPath() *SecretVersionUpsertBulk {
	return u.Update(func(s *SecretVersionUpsert) {
		s.UpdateVaultPath()
	})
}

// SetComment sets the "comment" field.
func (u *SecretVersionUpsertBulk) SetComment(v string) *SecretVersionUpsertBulk {
	return u.Update(func(s *SecretVersionUpsert) {
		s.SetComment(v)
	})
}

// UpdateComment sets the "comment" field to the value that was provided on create.
func (u *SecretVersionUpsertBulk) UpdateComment() *SecretVersionUpsertBulk {
	return u.Update(func(s *SecretVersionUpsert) {
		s.UpdateComment()
	})
}

// ClearComment clears the value of the "comment" field.
func (u *SecretVersionUpsertBulk) ClearComment() *SecretVersionUpsertBulk {
	return u.Update(func(s *SecretVersionUpsert) {
		s.ClearComment()
	})
}

// SetChecksum sets the "checksum" field.
func (u *SecretVersionUpsertBulk) SetChecksum(v string) *SecretVersionUpsertBulk {
	return u.Update(func(s *SecretVersionUpsert) {
		s.SetChecksum(v)
	})
}

// UpdateChecksum sets the "checksum" field to the value that was provided on create.
func (u *SecretVersionUpsertBulk) UpdateChecksum() *SecretVersionUpsertBulk {
	return u.Update(func(s *SecretVersionUpsert) {
		s.UpdateChecksum()
	})
}

// Exec executes the query.
func (u *SecretVersionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SecretVersionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SecretVersionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SecretVersionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
