// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/go-tangra/go-tangra-warden/internal/data/ent/folder"
	"github.com/go-tangra/go-tangra-warden/internal/data/ent/permission"
	"github.com/go-tangra/go-tangra-warden/internal/data/ent/predicate"
	"github.com/go-tangra/go-tangra-warden/internal/data/ent/secret"
	"github.com/go-tangra/go-tangra-warden/internal/data/ent/secretversion"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SecretUpdate is the builder for updating Secret entities.
type SecretUpdate struct {
	config
	hooks     []Hook
	mutation  *SecretMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the SecretUpdate builder.
func (_u *SecretUpdate) Where(ps ...predicate.Secret) *SecretUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreateBy sets the "create_by" field.
func (_u *SecretUpdate) SetCreateBy(v uint32) *SecretUpdate {
	_u.mutation.ResetCreateBy()
	_u.mutation.SetCreateBy(v)
	return _u
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_u *SecretUpdate) SetNillableCreateBy(v *uint32) *SecretUpdate {
	if v != nil {
		_u.SetCreateBy(*v)
	}
	return _u
}

// AddCreateBy adds value to the "create_by" field.
func (_u *SecretUpdate) AddCreateBy(v int32) *SecretUpdate {
	_u.mutation.AddCreateBy(v)
	return _u
}

// ClearCreateBy clears the value of the "create_by" field.
func (_u *SecretUpdate) ClearCreateBy() *SecretUpdate {
	_u.mutation.ClearCreateBy()
	return _u
}

// SetUpdateBy sets the "update_by" field.
func (_u *SecretUpdate) SetUpdateBy(v uint32) *SecretUpdate {
	_u.mutation.ResetUpdateBy()
	_u.mutation.SetUpdateBy(v)
	return _u
}

// SetNillableUpdateBy sets the "update_by" field if the given value is not nil.
func (_u *SecretUpdate) SetNillableUpdateBy(v *uint32) *SecretUpdate {
	if v != nil {
		_u.SetUpdateBy(*v)
	}
	return _u
}

// AddUpdateBy adds value to the "update_by" field.
func (_u *SecretUpdate) AddUpdateBy(v int32) *SecretUpdate {
	_u.mutation.AddUpdateBy(v)
	return _u
}

// ClearUpdateBy clears the value of the "update_by" field.
func (_u *SecretUpdate) ClearUpdateBy() *SecretUpdate {
	_u.mutation.ClearUpdateBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *SecretUpdate) SetUpdateTime(v time.Time) *SecretUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *SecretUpdate) SetNillableUpdateTime(v *time.Time) *SecretUpdate {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *SecretUpdate) ClearUpdateTime() *SecretUpdate {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *SecretUpdate) SetDeleteTime(v time.Time) *SecretUpdate {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *SecretUpdate) SetNillableDeleteTime(v *time.Time) *SecretUpdate {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *SecretUpdate) ClearDeleteTime() *SecretUpdate {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetFolderID sets the "folder_id" field.
func (_u *SecretUpdate) SetFolderID(v string) *SecretUpdate {
	_u.mutation.SetFolderID(v)
	return _u
}

// SetNillableFolderID sets the "folder_id" field if the given value is not nil.
func (_u *SecretUpdate) SetNillableFolderID(v *string) *SecretUpdate {
	if v != nil {
		_u.SetFolderID(*v)
	}
	return _u
}

// ClearFolderID clears the value of the "folder_id" field.
func (_u *SecretUpdate) ClearFolderID() *SecretUpdate {
	_u.mutation.ClearFolderID()
	return _u
}

// SetName sets the "name" field.
func (_u *SecretUpdate) SetName(v string) *SecretUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SecretUpdate) SetNillableName(v *string) *SecretUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetUsername sets the "username" field.
func (_u *SecretUpdate) SetUsername(v string) *SecretUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *SecretUpdate) SetNillableUsername(v *string) *SecretUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// ClearUsername clears the value of the "username" field.
func (_u *SecretUpdate) ClearUsername() *SecretUpdate {
	_u.mutation.ClearUsername()
	return _u
}

// SetHostURL sets the "host_url" field.
func (_u *SecretUpdate) SetHostURL(v string) *SecretUpdate {
	_u.mutation.SetHostURL(v)
	return _u
}

// SetNillableHostURL sets the "host_url" field if the given value is not nil.
func (_u *SecretUpdate) SetNillableHostURL(v *string) *SecretUpdate {
	if v != nil {
		_u.SetHostURL(*v)
	}
	return _u
}

// ClearHostURL clears the value of the "host_url" field.
func (_u *SecretUpdate) ClearHostURL() *SecretUpdate {
	_u.mutation.ClearHostURL()
	return _u
}

// SetVaultPath sets the "vault_path" field.
func (_u *SecretUpdate) SetVaultPath(v string) *SecretUpdate {
	_u.mutation.SetVaultPath(v)
	return _u
}

// SetNillableVaultPath sets the "vault_path" field if the given value is not nil.
func (_u *SecretUpdate) SetNillableVaultPath(v *string) *SecretUpdate {
	if v != nil {
		_u.SetVaultPath(*v)
	}
	return _u
}

// SetCurrentVersion sets the "current_version" field.
func (_u *SecretUpdate) SetCurrentVersion(v int32) *SecretUpdate {
	_u.mutation.ResetCurrentVersion()
	_u.mutation.SetCurrentVersion(v)
	return _u
}

// SetNillableCurrentVersion sets the "current_version" field if the given value is not nil.
func (_u *SecretUpdate) SetNillableCurrentVersion(v *int32) *SecretUpdate {
	if v != nil {
		_u.SetCurrentVersion(*v)
	}
	return _u
}

// AddCurrentVersion adds value to the "current_version" field.
func (_u *SecretUpdate) AddCurrentVersion(v int32) *SecretUpdate {
	_u.mutation.AddCurrentVersion(v)
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *SecretUpdate) SetMetadata(v map[string]interface{}) *SecretUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *SecretUpdate) ClearMetadata() *SecretUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetDescription sets the "description" field.
func (_u *SecretUpdate) SetDescription(v string) *SecretUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *SecretUpdate) SetNillableDescription(v *string) *SecretUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *SecretUpdate) ClearDescription() *SecretUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetStatus sets the "status" field.
func (_u *SecretUpdate) SetStatus(v secret.Status) *SecretUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SecretUpdate) SetNillableStatus(v *secret.Status) *SecretUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetFolder sets the "folder" edge to the Folder entity.
func (_u *SecretUpdate) SetFolder(v *Folder) *SecretUpdate {
	return _u.SetFolderID(v.ID)
}

// AddVersionIDs adds the "versions" edge to the SecretVersion entity by IDs.
func (_u *SecretUpdate) AddVersionIDs(ids ...int) *SecretUpdate {
	_u.mutation.AddVersionIDs(ids...)
	return _u
}

// AddVersions adds the "versions" edges to the SecretVersion entity.
func (_u *SecretUpdate) AddVersions(v ...*SecretVersion) *SecretUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddVersionIDs(ids...)
}

// AddPermissionIDs adds the "permissions" edge to the Permission entity by IDs.
func (_u *SecretUpdate) AddPermissionIDs(ids ...int) *SecretUpdate {
	_u.mutation.AddPermissionIDs(ids...)
	return _u
}

// AddPermissions adds the "permissions" edges to the Permission entity.
func (_u *SecretUpdate) AddPermissions(v ...*Permission) *SecretUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPermissionIDs(ids...)
}

// Mutation returns the SecretMutation object of the builder.
func (_u *SecretUpdate) Mutation() *SecretMutation {
	return _u.mutation
}

// ClearFolder clears the "folder" edge to the Folder entity.
func (_u *SecretUpdate) ClearFolder() *SecretUpdate {
	_u.mutation.ClearFolder()
	return _u
}

// ClearVersions clears all "versions" edges to the SecretVersion entity.
func (_u *SecretUpdate) ClearVersions() *SecretUpdate {
	_u.mutation.ClearVersions()
	return _u
}

// RemoveVersionIDs removes the "versions" edge to SecretVersion entities by IDs.
func (_u *SecretUpdate) RemoveVersionIDs(ids ...int) *SecretUpdate {
	_u.mutation.RemoveVersionIDs(ids...)
	return _u
}

// RemoveVersions removes "versions" edges to SecretVersion entities.
func (_u *SecretUpdate) RemoveVersions(v ...*SecretVersion) *SecretUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveVersionIDs(ids...)
}

// ClearPermissions clears all "permissions" edges to the Permission entity.
func (_u *SecretUpdate) ClearPermissions() *SecretUpdate {
	_u.mutation.ClearPermissions()
	return _u
}

// RemovePermissionIDs removes the "permissions" edge to Permission entities by IDs.
func (_u *SecretUpdate) RemovePermissionIDs(ids ...int) *SecretUpdate {
	_u.mutation.RemovePermissionIDs(ids...)
	return _u
}

// RemovePermissions removes "permissions" edges to Permission entities.
func (_u *SecretUpdate) RemovePermissions(v ...*Permission) *SecretUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePermissionIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SecretUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SecretUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SecretUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SecretUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SecretUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := secret.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Secret.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Username(); ok {
		if err := secret.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "Secret.username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HostURL(); ok {
		if err := secret.HostURLValidator(v); err != nil {
			return &ValidationError{Name: "host_url", err: fmt.Errorf(`ent: validator failed for field "Secret.host_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VaultPath(); ok {
		if err := secret.VaultPathValidator(v); err != nil {
			return &ValidationError{Name: "vault_path", err: fmt.Errorf(`ent: validator failed for field "Secret.vault_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := secret.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Secret.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := secret.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Secret.status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SecretUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SecretUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SecretUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(secret.Table, secret.Columns, sqlgraph.NewFieldSpec(secret.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreateBy(); ok {
		_spec.SetField(secret.FieldCreateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreateBy(); ok {
		_spec.AddField(secret.FieldCreateBy, field.TypeUint32, value)
	}
	if _u.mutation.CreateByCleared() {
		_spec.ClearField(secret.FieldCreateBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdateBy(); ok {
		_spec.SetField(secret.FieldUpdateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdateBy(); ok {
		_spec.AddField(secret.FieldUpdateBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdateByCleared() {
		_spec.ClearField(secret.FieldUpdateBy, field.TypeUint32)
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(secret.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(secret.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(secret.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(secret.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(secret.FieldDeleteTime, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(secret.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(secret.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(secret.FieldUsername, field.TypeString, value)
	}
	if _u.mutation.UsernameCleared() {
		_spec.ClearField(secret.FieldUsername, field.TypeString)
	}
	if value, ok := _u.mutation.HostURL(); ok {
		_spec.SetField(secret.FieldHostURL, field.TypeString, value)
	}
	if _u.mutation.HostURLCleared() {
		_spec.ClearField(secret.FieldHostURL, field.TypeString)
	}
	if value, ok := _u.mutation.VaultPath(); ok {
		_spec.SetField(secret.FieldVaultPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.CurrentVersion(); ok {
		_spec.SetField(secret.FieldCurrentVersion, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedCurrentVersion(); ok {
		_spec.AddField(secret.FieldCurrentVersion, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(secret.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(secret.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(secret.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(secret.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(secret.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.FolderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   secret.FolderTable,
			Columns: []string{secret.FolderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(folder.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FolderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   secret.FolderTable,
			Columns: []string{secret.FolderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(folder.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.VersionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   secret.VersionsTable,
			Columns: []string{secret.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(secretversion.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedVersionsIDs(); len(nodes) > 0 && !_u.mutation.VersionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   secret.VersionsTable,
			Columns: []string{secret.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(secretversion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VersionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   secret.VersionsTable,
			Columns: []string{secret.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(secretversion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   secret.PermissionsTable,
			Columns: []string{secret.PermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(permission.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPermissionsIDs(); len(nodes) > 0 && !_u.mutation.PermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   secret.PermissionsTable,
			Columns: []string{secret.PermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(permission.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PermissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   secret.PermissionsTable,
			Columns: []string{secret.PermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(permission.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{secret.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SecretUpdateOne is the builder for updating a single Secret entity.
type SecretUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *SecretMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetCreateBy sets the "create_by" field.
func (_u *SecretUpdateOne) SetCreateBy(v uint32) *SecretUpdateOne {
	_u.mutation.ResetCreateBy()
	_u.mutation.SetCreateBy(v)
	return _u
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_u *SecretUpdateOne) SetNillableCreateBy(v *uint32) *SecretUpdateOne {
	if v != nil {
		_u.SetCreateBy(*v)
	}
	return _u
}

// AddCreateBy adds value to the "create_by" field.
func (_u *SecretUpdateOne) AddCreateBy(v int32) *SecretUpdateOne {
	_u.mutation.AddCreateBy(v)
	return _u
}

// ClearCreateBy clears the value of the "create_by" field.
func (_u *SecretUpdateOne) ClearCreateBy() *SecretUpdateOne {
	_u.mutation.ClearCreateBy()
	return _u
}

// SetUpdateBy sets the "update_by" field.
func (_u *SecretUpdateOne) SetUpdateBy(v uint32) *SecretUpdateOne {
	_u.mutation.ResetUpdateBy()
	_u.mutation.SetUpdateBy(v)
	return _u
}

// SetNillableUpdateBy sets the "update_by" field if the given value is not nil.
func (_u *SecretUpdateOne) SetNillableUpdateBy(v *uint32) *SecretUpdateOne {
	if v != nil {
		_u.SetUpdateBy(*v)
	}
	return _u
}

// AddUpdateBy adds value to the "update_by" field.
func (_u *SecretUpdateOne) AddUpdateBy(v int32) *SecretUpdateOne {
	_u.mutation.AddUpdateBy(v)
	return _u
}

// ClearUpdateBy clears the value of the "update_by" field.
func (_u *SecretUpdateOne) ClearUpdateBy() *SecretUpdateOne {
	_u.mutation.ClearUpdateBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *SecretUpdateOne) SetUpdateTime(v time.Time) *SecretUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *SecretUpdateOne) SetNillableUpdateTime(v *time.Time) *SecretUpdateOne {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *SecretUpdateOne) ClearUpdateTime() *SecretUpdateOne {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *SecretUpdateOne) SetDeleteTime(v time.Time) *SecretUpdateOne {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *SecretUpdateOne) SetNillableDeleteTime(v *time.Time) *SecretUpdateOne {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *SecretUpdateOne) ClearDeleteTime() *SecretUpdateOne {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetFolderID sets the "folder_id" field.
func (_u *SecretUpdateOne) SetFolderID(v string) *SecretUpdateOne {
	_u.mutation.SetFolderID(v)
	return _u
}

// SetNillableFolderID sets the "folder_id" field if the given value is not nil.
func (_u *SecretUpdateOne) SetNillableFolderID(v *string) *SecretUpdateOne {
	if v != nil {
		_u.SetFolderID(*v)
	}
	return _u
}

// ClearFolderID clears the value of the "folder_id" field.
func (_u *SecretUpdateOne) ClearFolderID() *SecretUpdateOne {
	_u.mutation.ClearFolderID()
	return _u
}

// SetName sets the "name" field.
func (_u *SecretUpdateOne) SetName(v string) *SecretUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SecretUpdateOne) SetNillableName(v *string) *SecretUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetUsername sets the "username" field.
func (_u *SecretUpdateOne) SetUsername(v string) *SecretUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *SecretUpdateOne) SetNillableUsername(v *string) *SecretUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// ClearUsername clears the value of the "username" field.
func (_u *SecretUpdateOne) ClearUsername() *SecretUpdateOne {
	_u.mutation.ClearUsername()
	return _u
}

// SetHostURL sets the "host_url" field.
func (_u *SecretUpdateOne) SetHostURL(v string) *SecretUpdateOne {
	_u.mutation.SetHostURL(v)
	return _u
}

// SetNillableHostURL sets the "host_url" field if the given value is not nil.
func (_u *SecretUpdateOne) SetNillableHostURL(v *string) *SecretUpdateOne {
	if v != nil {
		_u.SetHostURL(*v)
	}
	return _u
}

// ClearHostURL clears the value of the "host_url" field.
func (_u *SecretUpdateOne) ClearHostURL() *SecretUpdateOne {
	_u.mutation.ClearHostURL()
	return _u
}

// SetVaultPath sets the "vault_path" field.
func (_u *SecretUpdateOne) SetVaultPath(v string) *SecretUpdateOne {
	_u.mutation.SetVaultPath(v)
	return _u
}

// SetNillableVaultPath sets the "vault_path" field if the given value is not nil.
func (_u *SecretUpdateOne) SetNillableVaultPath(v *string) *SecretUpdateOne {
	if v != nil {
		_u.SetVaultPath(*v)
	}
	return _u
}

// SetCurrentVersion sets the "current_version" field.
func (_u *SecretUpdateOne) SetCurrentVersion(v int32) *SecretUpdateOne {
	_u.mutation.ResetCurrentVersion()
	_u.mutation.SetCurrentVersion(v)
	return _u
}

// SetNillableCurrentVersion sets the "current_version" field if the given value is not nil.
func (_u *SecretUpdateOne) SetNillableCurrentVersion(v *int32) *SecretUpdateOne {
	if v != nil {
		_u.SetCurrentVersion(*v)
	}
	return _u
}

// AddCurrentVersion adds value to the "current_version" field.
func (_u *SecretUpdateOne) AddCurrentVersion(v int32) *SecretUpdateOne {
	_u.mutation.AddCurrentVersion(v)
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *SecretUpdateOne) SetMetadata(v map[string]interface{}) *SecretUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *SecretUpdateOne) ClearMetadata() *SecretUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetDescription sets the "description" field.
func (_u *SecretUpdateOne) SetDescription(v string) *SecretUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *SecretUpdateOne) SetNillableDescription(v *string) *SecretUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *SecretUpdateOne) ClearDescription() *SecretUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetStatus sets the "status" field.
func (_u *SecretUpdateOne) SetStatus(v secret.Status) *SecretUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SecretUpdateOne) SetNillableStatus(v *secret.Status) *SecretUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetFolder sets the "folder" edge to the Folder entity.
func (_u *SecretUpdateOne) SetFolder(v *Folder) *SecretUpdateOne {
	return _u.SetFolderID(v.ID)
}

// AddVersionIDs adds the "versions" edge to the SecretVersion entity by IDs.
func (_u *SecretUpdateOne) AddVersionIDs(ids ...int) *SecretUpdateOne {
	_u.mutation.AddVersionIDs(ids...)
	return _u
}

// AddVersions adds the "versions" edges to the SecretVersion entity.
func (_u *SecretUpdateOne) AddVersions(v ...*SecretVersion) *SecretUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddVersionIDs(ids...)
}

// AddPermissionIDs adds the "permissions" edge to the Permission entity by IDs.
func (_u *SecretUpdateOne) AddPermissionIDs(ids ...int) *SecretUpdateOne {
	_u.mutation.AddPermissionIDs(ids...)
	return _u
}

// AddPermissions adds the "permissions" edges to the Permission entity.
func (_u *SecretUpdateOne) AddPermissions(v ...*Permission) *SecretUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPermissionIDs(ids...)
}

// Mutation returns the SecretMutation object of the builder.
func (_u *SecretUpdateOne) Mutation() *SecretMutation {
	return _u.mutation
}

// ClearFolder clears the "folder" edge to the Folder entity.
func (_u *SecretUpdateOne) ClearFolder() *SecretUpdateOne {
	_u.mutation.ClearFolder()
	return _u
}

// ClearVersions clears all "versions" edges to the SecretVersion entity.
func (_u *SecretUpdateOne) ClearVersions() *SecretUpdateOne {
	_u.mutation.ClearVersions()
	return _u
}

// RemoveVersionIDs removes the "versions" edge to SecretVersion entities by IDs.
func (_u *SecretUpdateOne) RemoveVersionIDs(ids ...int) *SecretUpdateOne {
	_u.mutation.RemoveVersionIDs(ids...)
	return _u
}

// RemoveVersions removes "versions" edges to SecretVersion entities.
func (_u *SecretUpdateOne) RemoveVersions(v ...*SecretVersion) *SecretUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveVersionIDs(ids...)
}

// ClearPermissions clears all "permissions" edges to the Permission entity.
func (_u *SecretUpdateOne) ClearPermissions() *SecretUpdateOne {
	_u.mutation.ClearPermissions()
	return _u
}

// RemovePermissionIDs removes the "permissions" edge to Permission entities by IDs.
func (_u *SecretUpdateOne) RemovePermissionIDs(ids ...int) *SecretUpdateOne {
	_u.mutation.RemovePermissionIDs(ids...)
	return _u
}

// RemovePermissions removes "permissions" edges to Permission entities.
func (_u *SecretUpdateOne) RemovePermissions(v ...*Permission) *SecretUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePermissionIDs(ids...)
}

// Where appends a list predicates to the SecretUpdate builder.
func (_u *SecretUpdateOne) Where(ps ...predicate.Secret) *SecretUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SecretUpdateOne) Select(field string, fields ...string) *SecretUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Secret entity.
func (_u *SecretUpdateOne) Save(ctx context.Context) (*Secret, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SecretUpdateOne) SaveX(ctx context.Context) *Secret {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SecretUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SecretUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SecretUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := secret.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Secret.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Username(); ok {
		if err := secret.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "Secret.username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HostURL(); ok {
		if err := secret.HostURLValidator(v); err != nil {
			return &ValidationError{Name: "host_url", err: fmt.Errorf(`ent: validator failed for field "Secret.host_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VaultPath(); ok {
		if err := secret.VaultPathValidator(v); err != nil {
			return &ValidationError{Name: "vault_path", err: fmt.Errorf(`ent: validator failed for field "Secret.vault_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := secret.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Secret.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := secret.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Secret.status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SecretUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SecretUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SecretUpdateOne) sqlSave(ctx context.Context) (_node *Secret, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(secret.Table, secret.Columns, sqlgraph.NewFieldSpec(secret.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Secret.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, secret.FieldID)
		for _, f := range fields {
			if !secret.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != secret.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreateBy(); ok {
		_spec.SetField(secret.FieldCreateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreateBy(); ok {
		_spec.AddField(secret.FieldCreateBy, field.TypeUint32, value)
	}
	if _u.mutation.CreateByCleared() {
		_spec.ClearField(secret.FieldCreateBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdateBy(); ok {
		_spec.SetField(secret.FieldUpdateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdateBy(); ok {
		_spec.AddField(secret.FieldUpdateBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdateByCleared() {
		_spec.ClearField(secret.FieldUpdateBy, field.TypeUint32)
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(secret.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(secret.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(secret.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(secret.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(secret.FieldDeleteTime, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(secret.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(secret.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(secret.FieldUsername, field.TypeString, value)
	}
	if _u.mutation.UsernameCleared() {
		_spec.ClearField(secret.FieldUsername, field.TypeString)
	}
	if value, ok := _u.mutation.HostURL(); ok {
		_spec.SetField(secret.FieldHostURL, field.TypeString, value)
	}
	if _u.mutation.HostURLCleared() {
		_spec.ClearField(secret.FieldHostURL, field.TypeString)
	}
	if value, ok := _u.mutation.VaultPath(); ok {
		_spec.SetField(secret.FieldVaultPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.CurrentVersion(); ok {
		_spec.SetField(secret.FieldCurrentVersion, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedCurrentVersion(); ok {
		_spec.AddField(secret.FieldCurrentVersion, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(secret.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(secret.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(secret.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(secret.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(secret.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.FolderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   secret.FolderTable,
			Columns: []string{secret.FolderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(folder.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FolderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   secret.FolderTable,
			Columns: []string{secret.FolderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(folder.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.VersionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   secret.VersionsTable,
			Columns: []string{secret.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(secretversion.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedVersionsIDs(); len(nodes) > 0 && !_u.mutation.VersionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   secret.VersionsTable,
			Columns: []string{secret.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(secretversion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VersionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   secret.VersionsTable,
			Columns: []string{secret.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(secretversion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   secret.PermissionsTable,
			Columns: []string{secret.PermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(permission.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPermissionsIDs(); len(nodes) > 0 && !_u.mutation.PermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   secret.PermissionsTable,
			Columns: []string{secret.PermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(permission.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PermissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   secret.PermissionsTable,
			Columns: []string{secret.PermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(permission.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Secret{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{secret.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
