// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-warden/internal/data/ent/folder"
	"github.com/go-tangra/go-tangra-warden/internal/data/ent/permission"
	"github.com/go-tangra/go-tangra-warden/internal/data/ent/secret"
	"github.com/go-tangra/go-tangra-warden/internal/data/ent/secretversion"
)

// SecretCreate is the builder for creating a Secret entity.
type SecretCreate struct {
	config
	mutation *SecretMutation
	hooks    []Hook
}

// SetCreateBy sets the "create_by" field.
func (_c *SecretCreate) SetCreateBy(v uint32) *SecretCreate {
	_c.mutation.SetCreateBy(v)
	return _c
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_c *SecretCreate) SetNillableCreateBy(v *uint32) *SecretCreate {
	if v != nil {
		_c.SetCreateBy(*v)
	}
	return _c
}

// SetUpdateBy sets the "update_by" field.
func (_c *SecretCreate) SetUpdateBy(v uint32) *SecretCreate {
	_c.mutation.SetUpdateBy(v)
	return _c
}

// SetNillableUpdateBy sets the "update_by" field if the given value is not nil.
func (_c *SecretCreate) SetNillableUpdateBy(v *uint32) *SecretCreate {
	if v != nil {
		_c.SetUpdateBy(*v)
	}
	return _c
}

// SetCreateTime sets the "create_time" field.
func (_c *SecretCreate) SetCreateTime(v time.Time) *SecretCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *SecretCreate) SetNillableCreateTime(v *time.Time) *SecretCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *SecretCreate) SetUpdateTime(v time.Time) *SecretCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *SecretCreate) SetNillableUpdateTime(v *time.Time) *SecretCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetDeleteTime sets the "delete_time" field.
func (_c *SecretCreate) SetDeleteTime(v time.Time) *SecretCreate {
	_c.mutation.SetDeleteTime(v)
	return _c
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_c *SecretCreate) SetNillableDeleteTime(v *time.Time) *SecretCreate {
	if v != nil {
		_c.SetDeleteTime(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *SecretCreate) SetTenantID(v uint32) *SecretCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *SecretCreate) SetNillableTenantID(v *uint32) *SecretCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetFolderID sets the "folder_id" field.
func (_c *SecretCreate) SetFolderID(v string) *SecretCreate {
	_c.mutation.SetFolderID(v)
	return _c
}

// SetNillableFolderID sets the "folder_id" field if the given value is not nil.
func (_c *SecretCreate) SetNillableFolderID(v *string) *SecretCreate {
	if v != nil {
		_c.SetFolderID(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *SecretCreate) SetName(v string) *SecretCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetUsername sets the "username" field.
func (_c *SecretCreate) SetUsername(v string) *SecretCreate {
	_c.mutation.SetUsername(v)
	return _c
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_c *SecretCreate) SetNillableUsername(v *string) *SecretCreate {
	if v != nil {
		_c.SetUsername(*v)
	}
	return _c
}

// SetHostURL sets the "host_url" field.
func (_c *SecretCreate) SetHostURL(v string) *SecretCreate {
	_c.mutation.SetHostURL(v)
	return _c
}

// SetNillableHostURL sets the "host_url" field if the given value is not nil.
func (_c *SecretCreate) SetNillableHostURL(v *string) *SecretCreate {
	if v != nil {
		_c.SetHostURL(*v)
	}
	return _c
}

// SetVaultPath sets the "vault_path" field.
func (_c *SecretCreate) SetVaultPath(v string) *SecretCreate {
	_c.mutation.SetVaultPath(v)
	return _c
}

// SetCurrentVersion sets the "current_version" field.
func (_c *SecretCreate) SetCurrentVersion(v int32) *SecretCreate {
	_c.mutation.SetCurrentVersion(v)
	return _c
}

// SetNillableCurrentVersion sets the "current_version" field if the given value is not nil.
func (_c *SecretCreate) SetNillableCurrentVersion(v *int32) *SecretCreate {
	if v != nil {
		_c.SetCurrentVersion(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *SecretCreate) SetMetadata(v map[string]interface{}) *SecretCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *SecretCreate) SetDescription(v string) *SecretCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *SecretCreate) SetNillableDescription(v *string) *SecretCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *SecretCreate) SetStatus(v secret.Status) *SecretCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *SecretCreate) SetNillableStatus(v *secret.Status) *SecretCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetHasTotp sets the "has_totp" field.
func (_c *SecretCreate) SetHasTotp(v bool) *SecretCreate {
	_c.mutation.SetHasTotp(v)
	return _c
}

// SetNillableHasTotp sets the "has_totp" field if the given value is not nil.
func (_c *SecretCreate) SetNillableHasTotp(v *bool) *SecretCreate {
	if v != nil {
		_c.SetHasTotp(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SecretCreate) SetID(v string) *SecretCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetFolder sets the "folder" edge to the Folder entity.
func (_c *SecretCreate) SetFolder(v *Folder) *SecretCreate {
	return _c.SetFolderID(v.ID)
}

// AddVersionIDs adds the "versions" edge to the SecretVersion entity by IDs.
func (_c *SecretCreate) AddVersionIDs(ids ...int) *SecretCreate {
	_c.mutation.AddVersionIDs(ids...)
	return _c
}

// AddVersions adds the "versions" edges to the SecretVersion entity.
func (_c *SecretCreate) AddVersions(v ...*SecretVersion) *SecretCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddVersionIDs(ids...)
}

// AddPermissionIDs adds the "permissions" edge to the Permission entity by IDs.
func (_c *SecretCreate) AddPermissionIDs(ids ...int) *SecretCreate {
	_c.mutation.AddPermissionIDs(ids...)
	return _c
}

// AddPermissions adds the "permissions" edges to the Permission entity.
func (_c *SecretCreate) AddPermissions(v ...*Permission) *SecretCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPermissionIDs(ids...)
}

// Mutation returns the SecretMutation object of the builder.
func (_c *SecretCreate) Mutation() *SecretMutation {
	return _c.mutation
}

// Save creates the Secret in the database.
func (_c *SecretCreate) Save(ctx context.Context) (*Secret, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SecretCreate) SaveX(ctx context.Context) *Secret {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SecretCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SecretCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SecretCreate) defaults() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := secret.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.CurrentVersion(); !ok {
		v := secret.DefaultCurrentVersion
		_c.mutation.SetCurrentVersion(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := secret.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.HasTotp(); !ok {
		v := secret.DefaultHasTotp
		_c.mutation.SetHasTotp(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *SecretCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Secret.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := secret.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Secret.name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Username(); ok {
		if err := secret.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "Secret.username": %w`, err)}
		}
	}
	if v, ok := _c.mutation.HostURL(); ok {
		if err := secret.HostURLValidator(v); err != nil {
			return &ValidationError{Name: "host_url", err: fmt.Errorf(`ent: validator failed for field "Secret.host_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.VaultPath(); !ok {
		return &ValidationError{Name: "vault_path", err: errors.New(`ent: missing required field "Secret.vault_path"`)}
	}
	if v, ok := _c.mutation.VaultPath(); ok {
		if err := secret.VaultPathValidator(v); err != nil {
			return &ValidationError{Name: "vault_path", err: fmt.Errorf(`ent: validator failed for field "Secret.vault_path": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CurrentVersion(); !ok {
		return &ValidationError{Name: "current_version", err: errors.New(`ent: missing required field "Secret.current_version"`)}
	}
	if v, ok := _c.mutation.Description(); ok {
		if err := secret.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Secret.description": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Secret.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := secret.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Secret.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.HasTotp(); !ok {
		return &ValidationError{Name: "has_totp", err: errors.New(`ent: missing required field "Secret.has_totp"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := secret.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Secret.id": %w`, err)}
		}
	}
	return nil
}

func (_c *SecretCreate) sqlSave(ctx context.Context) (*Secret, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Secret.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SecretCreate) createSpec() (*Secret, *sqlgraph.CreateSpec) {
	var (
		_node = &Secret{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(secret.Table, sqlgraph.NewFieldSpec(secret.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreateBy(); ok {
		_spec.SetField(secret.FieldCreateBy, field.TypeUint32, value)
		_node.CreateBy = &value
	}
	if value, ok := _c.mutation.UpdateBy(); ok {
		_spec.SetField(secret.FieldUpdateBy, field.TypeUint32, value)
		_node.UpdateBy = &value
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(secret.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = &value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(secret.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = &value
	}
	if value, ok := _c.mutation.DeleteTime(); ok {
		_spec.SetField(secret.FieldDeleteTime, field.TypeTime, value)
		_node.DeleteTime = &value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(secret.FieldTenantID, field.TypeUint32, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(secret.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Username(); ok {
		_spec.SetField(secret.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := _c.mutation.HostURL(); ok {
		_spec.SetField(secret.FieldHostURL, field.TypeString, value)
		_node.HostURL = value
	}
	if value, ok := _c.mutation.VaultPath(); ok {
		_spec.SetField(secret.FieldVaultPath, field.TypeString, value)
		_node.VaultPath = value
	}
	if value, ok := _c.mutation.CurrentVersion(); ok {
		_spec.SetField(secret.FieldCurrentVersion, field.TypeInt32, value)
		_node.CurrentVersion = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(secret.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(secret.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(secret.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.HasTotp(); ok {
		_spec.SetField(secret.FieldHasTotp, field.TypeBool, value)
		_node.HasTotp = value
	}
	if nodes := _c.mutation.FolderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   secret.FolderTable,
			Columns: []string{secret.FolderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(folder.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.FolderID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.VersionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   secret.VersionsTable,
			Columns: []string{secret.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(secretversion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PermissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   secret.PermissionsTable,
			Columns: []string{secret.PermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(permission.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SecretCreateBulk is the builder for creating many Secret entities in bulk.
type SecretCreateBulk struct {
	config
	err      error
	builders []*SecretCreate
}

// Save creates the Secret entities in the database.
func (_c *SecretCreateBulk) Save(ctx context.Context) ([]*Secret, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Secret, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SecretMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SecretCreateBulk) SaveX(ctx context.Context) []*Secret {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SecretCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SecretCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
