// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"github.com/go-tangra/go-tangra-warden/internal/data/ent/folder"
	"github.com/go-tangra/go-tangra-warden/internal/data/ent/secret"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Secret is the model entity for the Secret schema.
type Secret struct {
	config `json:"-"`
	// ID of the ent.
	// UUID primary key
	ID string `json:"id,omitempty"`
	// 创建者ID
	CreateBy *uint32 `json:"create_by,omitempty"`
	// 更新者ID
	UpdateBy *uint32 `json:"update_by,omitempty"`
	// 创建时间
	CreateTime *time.Time `json:"create_time,omitempty"`
	// 更新时间
	UpdateTime *time.Time `json:"update_time,omitempty"`
	// 删除时间
	DeleteTime *time.Time `json:"delete_time,omitempty"`
	// 租户ID
	TenantID *uint32 `json:"tenant_id,omitempty"`
	// Parent folder ID (null for root-level secrets)
	FolderID *string `json:"folder_id,omitempty"`
	// Secret name
	Name string `json:"name,omitempty"`
	// Associated username
	Username string `json:"username,omitempty"`
	// Host/URL associated with the secret
	HostURL string `json:"host_url,omitempty"`
	// Reference path to HashiCorp Vault
	VaultPath string `json:"vault_path,omitempty"`
	// Current active version number
	CurrentVersion int32 `json:"current_version,omitempty"`
	// Custom fields, notes, tags (JSON)
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// Description
	Description string `json:"description,omitempty"`
	// Secret status
	Status secret.Status `json:"status,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SecretQuery when eager-loading is set.
	Edges        SecretEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SecretEdges holds the relations/edges for other nodes in the graph.
type SecretEdges struct {
	// Parent folder
	Folder *Folder `json:"folder,omitempty"`
	// Secret versions
	Versions []*SecretVersion `json:"versions,omitempty"`
	// Permissions on this secret
	Permissions []*Permission `json:"permissions,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// FolderOrErr returns the Folder value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SecretEdges) FolderOrErr() (*Folder, error) {
	if e.Folder != nil {
		return e.Folder, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: folder.Label}
	}
	return nil, &NotLoadedError{edge: "folder"}
}

// VersionsOrErr returns the Versions value or an error if the edge
// was not loaded in eager-loading.
func (e SecretEdges) VersionsOrErr() ([]*SecretVersion, error) {
	if e.loadedTypes[1] {
		return e.Versions, nil
	}
	return nil, &NotLoadedError{edge: "versions"}
}

// PermissionsOrErr returns the Permissions value or an error if the edge
// was not loaded in eager-loading.
func (e SecretEdges) PermissionsOrErr() ([]*Permission, error) {
	if e.loadedTypes[2] {
		return e.Permissions, nil
	}
	return nil, &NotLoadedError{edge: "permissions"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Secret) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case secret.FieldMetadata:
			values[i] = new([]byte)
		case secret.FieldCreateBy, secret.FieldUpdateBy, secret.FieldTenantID, secret.FieldCurrentVersion:
			values[i] = new(sql.NullInt64)
		case secret.FieldID, secret.FieldFolderID, secret.FieldName, secret.FieldUsername, secret.FieldHostURL, secret.FieldVaultPath, secret.FieldDescription, secret.FieldStatus:
			values[i] = new(sql.NullString)
		case secret.FieldCreateTime, secret.FieldUpdateTime, secret.FieldDeleteTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Secret fields.
func (_m *Secret) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case secret.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case secret.FieldCreateBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field create_by", values[i])
			} else if value.Valid {
				_m.CreateBy = new(uint32)
				*_m.CreateBy = uint32(value.Int64)
			}
		case secret.FieldUpdateBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field update_by", values[i])
			} else if value.Valid {
				_m.UpdateBy = new(uint32)
				*_m.UpdateBy = uint32(value.Int64)
			}
		case secret.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = new(time.Time)
				*_m.CreateTime = value.Time
			}
		case secret.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = new(time.Time)
				*_m.UpdateTime = value.Time
			}
		case secret.FieldDeleteTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field delete_time", values[i])
			} else if value.Valid {
				_m.DeleteTime = new(time.Time)
				*_m.DeleteTime = value.Time
			}
		case secret.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = new(uint32)
				*_m.TenantID = uint32(value.Int64)
			}
		case secret.FieldFolderID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field folder_id", values[i])
			} else if value.Valid {
				_m.FolderID = new(string)
				*_m.FolderID = value.String
			}
		case secret.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case secret.FieldUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field username", values[i])
			} else if value.Valid {
				_m.Username = value.String
			}
		case secret.FieldHostURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field host_url", values[i])
			} else if value.Valid {
				_m.HostURL = value.String
			}
		case secret.FieldVaultPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field vault_path", values[i])
			} else if value.Valid {
				_m.VaultPath = value.String
			}
		case secret.FieldCurrentVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field current_version", values[i])
			} else if value.Valid {
				_m.CurrentVersion = int32(value.Int64)
			}
		case secret.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case secret.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case secret.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = secret.Status(value.String)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Secret.
// This includes values selected through modifiers, order, etc.
func (_m *Secret) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryFolder queries the "folder" edge of the Secret entity.
func (_m *Secret) QueryFolder() *FolderQuery {
	return NewSecretClient(_m.config).QueryFolder(_m)
}

// QueryVersions queries the "versions" edge of the Secret entity.
func (_m *Secret) QueryVersions() *SecretVersionQuery {
	return NewSecretClient(_m.config).QueryVersions(_m)
}

// QueryPermissions queries the "permissions" edge of the Secret entity.
func (_m *Secret) QueryPermissions() *PermissionQuery {
	return NewSecretClient(_m.config).QueryPermissions(_m)
}

// Update returns a builder for updating this Secret.
// Note that you need to call Secret.Unwrap() before calling this method if this Secret
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Secret) Update() *SecretUpdateOne {
	return NewSecretClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Secret entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Secret) Unwrap() *Secret {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Secret is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Secret) String() string {
	var builder strings.Builder
	builder.WriteString("Secret(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.CreateBy; v != nil {
		builder.WriteString("create_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UpdateBy; v != nil {
		builder.WriteString("update_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CreateTime; v != nil {
		builder.WriteString("create_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdateTime; v != nil {
		builder.WriteString("update_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DeleteTime; v != nil {
		builder.WriteString("delete_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.TenantID; v != nil {
		builder.WriteString("tenant_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.FolderID; v != nil {
		builder.WriteString("folder_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("username=")
	builder.WriteString(_m.Username)
	builder.WriteString(", ")
	builder.WriteString("host_url=")
	builder.WriteString(_m.HostURL)
	builder.WriteString(", ")
	builder.WriteString("vault_path=")
	builder.WriteString(_m.VaultPath)
	builder.WriteString(", ")
	builder.WriteString("current_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.CurrentVersion))
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteByte(')')
	return builder.String()
}

// Secrets is a parsable slice of Secret.
type Secrets []*Secret
