// Code generated by ent, DO NOT EDIT.

package secret

import (
	"time"

	"github.com/go-tangra/go-tangra-warden/internal/data/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Secret {
	return predicate.Secret(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Secret {
	return predicate.Secret(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Secret {
	return predicate.Secret(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Secret {
	return predicate.Secret(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Secret {
	return predicate.Secret(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Secret {
	return predicate.Secret(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Secret {
	return predicate.Secret(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Secret {
	return predicate.Secret(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Secret {
	return predicate.Secret(sql.FieldContainsFold(FieldID, id))
}

// CreateBy applies equality check predicate on the "create_by" field. It's identical to CreateByEQ.
func CreateBy(v uint32) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldCreateBy, v))
}

// UpdateBy applies equality check predicate on the "update_by" field. It's identical to UpdateByEQ.
func UpdateBy(v uint32) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldUpdateBy, v))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldUpdateTime, v))
}

// DeleteTime applies equality check predicate on the "delete_time" field. It's identical to DeleteTimeEQ.
func DeleteTime(v time.Time) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldDeleteTime, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uint32) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldTenantID, v))
}

// FolderID applies equality check predicate on the "folder_id" field. It's identical to FolderIDEQ.
func FolderID(v string) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldFolderID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldName, v))
}

// Username applies equality check predicate on the "username" field. It's identical to UsernameEQ.
func Username(v string) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldUsername, v))
}

// HostURL applies equality check predicate on the "host_url" field. It's identical to HostURLEQ.
func HostURL(v string) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldHostURL, v))
}

// VaultPath applies equality check predicate on the "vault_path" field. It's identical to VaultPathEQ.
func VaultPath(v string) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldVaultPath, v))
}

// CurrentVersion applies equality check predicate on the "current_version" field. It's identical to CurrentVersionEQ.
func CurrentVersion(v int32) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldCurrentVersion, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldDescription, v))
}

// CreateByEQ applies the EQ predicate on the "create_by" field.
func CreateByEQ(v uint32) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldCreateBy, v))
}

// CreateByNEQ applies the NEQ predicate on the "create_by" field.
func CreateByNEQ(v uint32) predicate.Secret {
	return predicate.Secret(sql.FieldNEQ(FieldCreateBy, v))
}

// CreateByIn applies the In predicate on the "create_by" field.
func CreateByIn(vs ...uint32) predicate.Secret {
	return predicate.Secret(sql.FieldIn(FieldCreateBy, vs...))
}

// CreateByNotIn applies the NotIn predicate on the "create_by" field.
func CreateByNotIn(vs ...uint32) predicate.Secret {
	return predicate.Secret(sql.FieldNotIn(FieldCreateBy, vs...))
}

// CreateByGT applies the GT predicate on the "create_by" field.
func CreateByGT(v uint32) predicate.Secret {
	return predicate.Secret(sql.FieldGT(FieldCreateBy, v))
}

// CreateByGTE applies the GTE predicate on the "create_by" field.
func CreateByGTE(v uint32) predicate.Secret {
	return predicate.Secret(sql.FieldGTE(FieldCreateBy, v))
}

// CreateByLT applies the LT predicate on the "create_by" field.
func CreateByLT(v uint32) predicate.Secret {
	return predicate.Secret(sql.FieldLT(FieldCreateBy, v))
}

// CreateByLTE applies the LTE predicate on the "create_by" field.
func CreateByLTE(v uint32) predicate.Secret {
	return predicate.Secret(sql.FieldLTE(FieldCreateBy, v))
}

// CreateByIsNil applies the IsNil predicate on the "create_by" field.
func CreateByIsNil() predicate.Secret {
	return predicate.Secret(sql.FieldIsNull(FieldCreateBy))
}

// CreateByNotNil applies the NotNil predicate on the "create_by" field.
func CreateByNotNil() predicate.Secret {
	return predicate.Secret(sql.FieldNotNull(FieldCreateBy))
}

// UpdateByEQ applies the EQ predicate on the "update_by" field.
func UpdateByEQ(v uint32) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldUpdateBy, v))
}

// UpdateByNEQ applies the NEQ predicate on the "update_by" field.
func UpdateByNEQ(v uint32) predicate.Secret {
	return predicate.Secret(sql.FieldNEQ(FieldUpdateBy, v))
}

// UpdateByIn applies the In predicate on the "update_by" field.
func UpdateByIn(vs ...uint32) predicate.Secret {
	return predicate.Secret(sql.FieldIn(FieldUpdateBy, vs...))
}

// UpdateByNotIn applies the NotIn predicate on the "update_by" field.
func UpdateByNotIn(vs ...uint32) predicate.Secret {
	return predicate.Secret(sql.FieldNotIn(FieldUpdateBy, vs...))
}

// UpdateByGT applies the GT predicate on the "update_by" field.
func UpdateByGT(v uint32) predicate.Secret {
	return predicate.Secret(sql.FieldGT(FieldUpdateBy, v))
}

// UpdateByGTE applies the GTE predicate on the "update_by" field.
func UpdateByGTE(v uint32) predicate.Secret {
	return predicate.Secret(sql.FieldGTE(FieldUpdateBy, v))
}

// UpdateByLT applies the LT predicate on the "update_by" field.
func UpdateByLT(v uint32) predicate.Secret {
	return predicate.Secret(sql.FieldLT(FieldUpdateBy, v))
}

// UpdateByLTE applies the LTE predicate on the "update_by" field.
func UpdateByLTE(v uint32) predicate.Secret {
	return predicate.Secret(sql.FieldLTE(FieldUpdateBy, v))
}

// UpdateByIsNil applies the IsNil predicate on the "update_by" field.
func UpdateByIsNil() predicate.Secret {
	return predicate.Secret(sql.FieldIsNull(FieldUpdateBy))
}

// UpdateByNotNil applies the NotNil predicate on the "update_by" field.
func UpdateByNotNil() predicate.Secret {
	return predicate.Secret(sql.FieldNotNull(FieldUpdateBy))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.Secret {
	return predicate.Secret(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.Secret {
	return predicate.Secret(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.Secret {
	return predicate.Secret(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.Secret {
	return predicate.Secret(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.Secret {
	return predicate.Secret(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.Secret {
	return predicate.Secret(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.Secret {
	return predicate.Secret(sql.FieldLTE(FieldCreateTime, v))
}

// CreateTimeIsNil applies the IsNil predicate on the "create_time" field.
func CreateTimeIsNil() predicate.Secret {
	return predicate.Secret(sql.FieldIsNull(FieldCreateTime))
}

// CreateTimeNotNil applies the NotNil predicate on the "create_time" field.
func CreateTimeNotNil() predicate.Secret {
	return predicate.Secret(sql.FieldNotNull(FieldCreateTime))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.Secret {
	return predicate.Secret(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.Secret {
	return predicate.Secret(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.Secret {
	return predicate.Secret(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.Secret {
	return predicate.Secret(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.Secret {
	return predicate.Secret(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.Secret {
	return predicate.Secret(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.Secret {
	return predicate.Secret(sql.FieldLTE(FieldUpdateTime, v))
}

// UpdateTimeIsNil applies the IsNil predicate on the "update_time" field.
func UpdateTimeIsNil() predicate.Secret {
	return predicate.Secret(sql.FieldIsNull(FieldUpdateTime))
}

// UpdateTimeNotNil applies the NotNil predicate on the "update_time" field.
func UpdateTimeNotNil() predicate.Secret {
	return predicate.Secret(sql.FieldNotNull(FieldUpdateTime))
}

// DeleteTimeEQ applies the EQ predicate on the "delete_time" field.
func DeleteTimeEQ(v time.Time) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldDeleteTime, v))
}

// DeleteTimeNEQ applies the NEQ predicate on the "delete_time" field.
func DeleteTimeNEQ(v time.Time) predicate.Secret {
	return predicate.Secret(sql.FieldNEQ(FieldDeleteTime, v))
}

// DeleteTimeIn applies the In predicate on the "delete_time" field.
func DeleteTimeIn(vs ...time.Time) predicate.Secret {
	return predicate.Secret(sql.FieldIn(FieldDeleteTime, vs...))
}

// DeleteTimeNotIn applies the NotIn predicate on the "delete_time" field.
func DeleteTimeNotIn(vs ...time.Time) predicate.Secret {
	return predicate.Secret(sql.FieldNotIn(FieldDeleteTime, vs...))
}

// DeleteTimeGT applies the GT predicate on the "delete_time" field.
func DeleteTimeGT(v time.Time) predicate.Secret {
	return predicate.Secret(sql.FieldGT(FieldDeleteTime, v))
}

// DeleteTimeGTE applies the GTE predicate on the "delete_time" field.
func DeleteTimeGTE(v time.Time) predicate.Secret {
	return predicate.Secret(sql.FieldGTE(FieldDeleteTime, v))
}

// DeleteTimeLT applies the LT predicate on the "delete_time" field.
func DeleteTimeLT(v time.Time) predicate.Secret {
	return predicate.Secret(sql.FieldLT(FieldDeleteTime, v))
}

// DeleteTimeLTE applies the LTE predicate on the "delete_time" field.
func DeleteTimeLTE(v time.Time) predicate.Secret {
	return predicate.Secret(sql.FieldLTE(FieldDeleteTime, v))
}

// DeleteTimeIsNil applies the IsNil predicate on the "delete_time" field.
func DeleteTimeIsNil() predicate.Secret {
	return predicate.Secret(sql.FieldIsNull(FieldDeleteTime))
}

// DeleteTimeNotNil applies the NotNil predicate on the "delete_time" field.
func DeleteTimeNotNil() predicate.Secret {
	return predicate.Secret(sql.FieldNotNull(FieldDeleteTime))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uint32) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uint32) predicate.Secret {
	return predicate.Secret(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uint32) predicate.Secret {
	return predicate.Secret(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uint32) predicate.Secret {
	return predicate.Secret(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uint32) predicate.Secret {
	return predicate.Secret(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uint32) predicate.Secret {
	return predicate.Secret(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uint32) predicate.Secret {
	return predicate.Secret(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uint32) predicate.Secret {
	return predicate.Secret(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDIsNil applies the IsNil predicate on the "tenant_id" field.
func TenantIDIsNil() predicate.Secret {
	return predicate.Secret(sql.FieldIsNull(FieldTenantID))
}

// TenantIDNotNil applies the NotNil predicate on the "tenant_id" field.
func TenantIDNotNil() predicate.Secret {
	return predicate.Secret(sql.FieldNotNull(FieldTenantID))
}

// FolderIDEQ applies the EQ predicate on the "folder_id" field.
func FolderIDEQ(v string) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldFolderID, v))
}

// FolderIDNEQ applies the NEQ predicate on the "folder_id" field.
func FolderIDNEQ(v string) predicate.Secret {
	return predicate.Secret(sql.FieldNEQ(FieldFolderID, v))
}

// FolderIDIn applies the In predicate on the "folder_id" field.
func FolderIDIn(vs ...string) predicate.Secret {
	return predicate.Secret(sql.FieldIn(FieldFolderID, vs...))
}

// FolderIDNotIn applies the NotIn predicate on the "folder_id" field.
func FolderIDNotIn(vs ...string) predicate.Secret {
	return predicate.Secret(sql.FieldNotIn(FieldFolderID, vs...))
}

// FolderIDGT applies the GT predicate on the "folder_id" field.
func FolderIDGT(v string) predicate.Secret {
	return predicate.Secret(sql.FieldGT(FieldFolderID, v))
}

// FolderIDGTE applies the GTE predicate on the "folder_id" field.
func FolderIDGTE(v string) predicate.Secret {
	return predicate.Secret(sql.FieldGTE(FieldFolderID, v))
}

// FolderIDLT applies the LT predicate on the "folder_id" field.
func FolderIDLT(v string) predicate.Secret {
	return predicate.Secret(sql.FieldLT(FieldFolderID, v))
}

// FolderIDLTE applies the LTE predicate on the "folder_id" field.
func FolderIDLTE(v string) predicate.Secret {
	return predicate.Secret(sql.FieldLTE(FieldFolderID, v))
}

// FolderIDContains applies the Contains predicate on the "folder_id" field.
func FolderIDContains(v string) predicate.Secret {
	return predicate.Secret(sql.FieldContains(FieldFolderID, v))
}

// FolderIDHasPrefix applies the HasPrefix predicate on the "folder_id" field.
func FolderIDHasPrefix(v string) predicate.Secret {
	return predicate.Secret(sql.FieldHasPrefix(FieldFolderID, v))
}

// FolderIDHasSuffix applies the HasSuffix predicate on the "folder_id" field.
func FolderIDHasSuffix(v string) predicate.Secret {
	return predicate.Secret(sql.FieldHasSuffix(FieldFolderID, v))
}

// FolderIDIsNil applies the IsNil predicate on the "folder_id" field.
func FolderIDIsNil() predicate.Secret {
	return predicate.Secret(sql.FieldIsNull(FieldFolderID))
}

// FolderIDNotNil applies the NotNil predicate on the "folder_id" field.
func FolderIDNotNil() predicate.Secret {
	return predicate.Secret(sql.FieldNotNull(FieldFolderID))
}

// FolderIDEqualFold applies the EqualFold predicate on the "folder_id" field.
func FolderIDEqualFold(v string) predicate.Secret {
	return predicate.Secret(sql.FieldEqualFold(FieldFolderID, v))
}

// FolderIDContainsFold applies the ContainsFold predicate on the "folder_id" field.
func FolderIDContainsFold(v string) predicate.Secret {
	return predicate.Secret(sql.FieldContainsFold(FieldFolderID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Secret {
	return predicate.Secret(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Secret {
	return predicate.Secret(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Secret {
	return predicate.Secret(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Secret {
	return predicate.Secret(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Secret {
	return predicate.Secret(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Secret {
	return predicate.Secret(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Secret {
	return predicate.Secret(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Secret {
	return predicate.Secret(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Secret {
	return predicate.Secret(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Secret {
	return predicate.Secret(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Secret {
	return predicate.Secret(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Secret {
	return predicate.Secret(sql.FieldContainsFold(FieldName, v))
}

// UsernameEQ applies the EQ predicate on the "username" field.
func UsernameEQ(v string) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldUsername, v))
}

// UsernameNEQ applies the NEQ predicate on the "username" field.
func UsernameNEQ(v string) predicate.Secret {
	return predicate.Secret(sql.FieldNEQ(FieldUsername, v))
}

// UsernameIn applies the In predicate on the "username" field.
func UsernameIn(vs ...string) predicate.Secret {
	return predicate.Secret(sql.FieldIn(FieldUsername, vs...))
}

// UsernameNotIn applies the NotIn predicate on the "username" field.
func UsernameNotIn(vs ...string) predicate.Secret {
	return predicate.Secret(sql.FieldNotIn(FieldUsername, vs...))
}

// UsernameGT applies the GT predicate on the "username" field.
func UsernameGT(v string) predicate.Secret {
	return predicate.Secret(sql.FieldGT(FieldUsername, v))
}

// UsernameGTE applies the GTE predicate on the "username" field.
func UsernameGTE(v string) predicate.Secret {
	return predicate.Secret(sql.FieldGTE(FieldUsername, v))
}

// UsernameLT applies the LT predicate on the "username" field.
func UsernameLT(v string) predicate.Secret {
	return predicate.Secret(sql.FieldLT(FieldUsername, v))
}

// UsernameLTE applies the LTE predicate on the "username" field.
func UsernameLTE(v string) predicate.Secret {
	return predicate.Secret(sql.FieldLTE(FieldUsername, v))
}

// UsernameContains applies the Contains predicate on the "username" field.
func UsernameContains(v string) predicate.Secret {
	return predicate.Secret(sql.FieldContains(FieldUsername, v))
}

// UsernameHasPrefix applies the HasPrefix predicate on the "username" field.
func UsernameHasPrefix(v string) predicate.Secret {
	return predicate.Secret(sql.FieldHasPrefix(FieldUsername, v))
}

// UsernameHasSuffix applies the HasSuffix predicate on the "username" field.
func UsernameHasSuffix(v string) predicate.Secret {
	return predicate.Secret(sql.FieldHasSuffix(FieldUsername, v))
}

// UsernameIsNil applies the IsNil predicate on the "username" field.
func UsernameIsNil() predicate.Secret {
	return predicate.Secret(sql.FieldIsNull(FieldUsername))
}

// UsernameNotNil applies the NotNil predicate on the "username" field.
func UsernameNotNil() predicate.Secret {
	return predicate.Secret(sql.FieldNotNull(FieldUsername))
}

// UsernameEqualFold applies the EqualFold predicate on the "username" field.
func UsernameEqualFold(v string) predicate.Secret {
	return predicate.Secret(sql.FieldEqualFold(FieldUsername, v))
}

// UsernameContainsFold applies the ContainsFold predicate on the "username" field.
func UsernameContainsFold(v string) predicate.Secret {
	return predicate.Secret(sql.FieldContainsFold(FieldUsername, v))
}

// HostURLEQ applies the EQ predicate on the "host_url" field.
func HostURLEQ(v string) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldHostURL, v))
}

// HostURLNEQ applies the NEQ predicate on the "host_url" field.
func HostURLNEQ(v string) predicate.Secret {
	return predicate.Secret(sql.FieldNEQ(FieldHostURL, v))
}

// HostURLIn applies the In predicate on the "host_url" field.
func HostURLIn(vs ...string) predicate.Secret {
	return predicate.Secret(sql.FieldIn(FieldHostURL, vs...))
}

// HostURLNotIn applies the NotIn predicate on the "host_url" field.
func HostURLNotIn(vs ...string) predicate.Secret {
	return predicate.Secret(sql.FieldNotIn(FieldHostURL, vs...))
}

// HostURLGT applies the GT predicate on the "host_url" field.
func HostURLGT(v string) predicate.Secret {
	return predicate.Secret(sql.FieldGT(FieldHostURL, v))
}

// HostURLGTE applies the GTE predicate on the "host_url" field.
func HostURLGTE(v string) predicate.Secret {
	return predicate.Secret(sql.FieldGTE(FieldHostURL, v))
}

// HostURLLT applies the LT predicate on the "host_url" field.
func HostURLLT(v string) predicate.Secret {
	return predicate.Secret(sql.FieldLT(FieldHostURL, v))
}

// HostURLLTE applies the LTE predicate on the "host_url" field.
func HostURLLTE(v string) predicate.Secret {
	return predicate.Secret(sql.FieldLTE(FieldHostURL, v))
}

// HostURLContains applies the Contains predicate on the "host_url" field.
func HostURLContains(v string) predicate.Secret {
	return predicate.Secret(sql.FieldContains(FieldHostURL, v))
}

// HostURLHasPrefix applies the HasPrefix predicate on the "host_url" field.
func HostURLHasPrefix(v string) predicate.Secret {
	return predicate.Secret(sql.FieldHasPrefix(FieldHostURL, v))
}

// HostURLHasSuffix applies the HasSuffix predicate on the "host_url" field.
func HostURLHasSuffix(v string) predicate.Secret {
	return predicate.Secret(sql.FieldHasSuffix(FieldHostURL, v))
}

// HostURLIsNil applies the IsNil predicate on the "host_url" field.
func HostURLIsNil() predicate.Secret {
	return predicate.Secret(sql.FieldIsNull(FieldHostURL))
}

// HostURLNotNil applies the NotNil predicate on the "host_url" field.
func HostURLNotNil() predicate.Secret {
	return predicate.Secret(sql.FieldNotNull(FieldHostURL))
}

// HostURLEqualFold applies the EqualFold predicate on the "host_url" field.
func HostURLEqualFold(v string) predicate.Secret {
	return predicate.Secret(sql.FieldEqualFold(FieldHostURL, v))
}

// HostURLContainsFold applies the ContainsFold predicate on the "host_url" field.
func HostURLContainsFold(v string) predicate.Secret {
	return predicate.Secret(sql.FieldContainsFold(FieldHostURL, v))
}

// VaultPathEQ applies the EQ predicate on the "vault_path" field.
func VaultPathEQ(v string) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldVaultPath, v))
}

// VaultPathNEQ applies the NEQ predicate on the "vault_path" field.
func VaultPathNEQ(v string) predicate.Secret {
	return predicate.Secret(sql.FieldNEQ(FieldVaultPath, v))
}

// VaultPathIn applies the In predicate on the "vault_path" field.
func VaultPathIn(vs ...string) predicate.Secret {
	return predicate.Secret(sql.FieldIn(FieldVaultPath, vs...))
}

// VaultPathNotIn applies the NotIn predicate on the "vault_path" field.
func VaultPathNotIn(vs ...string) predicate.Secret {
	return predicate.Secret(sql.FieldNotIn(FieldVaultPath, vs...))
}

// VaultPathGT applies the GT predicate on the "vault_path" field.
func VaultPathGT(v string) predicate.Secret {
	return predicate.Secret(sql.FieldGT(FieldVaultPath, v))
}

// VaultPathGTE applies the GTE predicate on the "vault_path" field.
func VaultPathGTE(v string) predicate.Secret {
	return predicate.Secret(sql.FieldGTE(FieldVaultPath, v))
}

// VaultPathLT applies the LT predicate on the "vault_path" field.
func VaultPathLT(v string) predicate.Secret {
	return predicate.Secret(sql.FieldLT(FieldVaultPath, v))
}

// VaultPathLTE applies the LTE predicate on the "vault_path" field.
func VaultPathLTE(v string) predicate.Secret {
	return predicate.Secret(sql.FieldLTE(FieldVaultPath, v))
}

// VaultPathContains applies the Contains predicate on the "vault_path" field.
func VaultPathContains(v string) predicate.Secret {
	return predicate.Secret(sql.FieldContains(FieldVaultPath, v))
}

// VaultPathHasPrefix applies the HasPrefix predicate on the "vault_path" field.
func VaultPathHasPrefix(v string) predicate.Secret {
	return predicate.Secret(sql.FieldHasPrefix(FieldVaultPath, v))
}

// VaultPathHasSuffix applies the HasSuffix predicate on the "vault_path" field.
func VaultPathHasSuffix(v string) predicate.Secret {
	return predicate.Secret(sql.FieldHasSuffix(FieldVaultPath, v))
}

// VaultPathEqualFold applies the EqualFold predicate on the "vault_path" field.
func VaultPathEqualFold(v string) predicate.Secret {
	return predicate.Secret(sql.FieldEqualFold(FieldVaultPath, v))
}

// VaultPathContainsFold applies the ContainsFold predicate on the "vault_path" field.
func VaultPathContainsFold(v string) predicate.Secret {
	return predicate.Secret(sql.FieldContainsFold(FieldVaultPath, v))
}

// CurrentVersionEQ applies the EQ predicate on the "current_version" field.
func CurrentVersionEQ(v int32) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldCurrentVersion, v))
}

// CurrentVersionNEQ applies the NEQ predicate on the "current_version" field.
func CurrentVersionNEQ(v int32) predicate.Secret {
	return predicate.Secret(sql.FieldNEQ(FieldCurrentVersion, v))
}

// CurrentVersionIn applies the In predicate on the "current_version" field.
func CurrentVersionIn(vs ...int32) predicate.Secret {
	return predicate.Secret(sql.FieldIn(FieldCurrentVersion, vs...))
}

// CurrentVersionNotIn applies the NotIn predicate on the "current_version" field.
func CurrentVersionNotIn(vs ...int32) predicate.Secret {
	return predicate.Secret(sql.FieldNotIn(FieldCurrentVersion, vs...))
}

// CurrentVersionGT applies the GT predicate on the "current_version" field.
func CurrentVersionGT(v int32) predicate.Secret {
	return predicate.Secret(sql.FieldGT(FieldCurrentVersion, v))
}

// CurrentVersionGTE applies the GTE predicate on the "current_version" field.
func CurrentVersionGTE(v int32) predicate.Secret {
	return predicate.Secret(sql.FieldGTE(FieldCurrentVersion, v))
}

// CurrentVersionLT applies the LT predicate on the "current_version" field.
func CurrentVersionLT(v int32) predicate.Secret {
	return predicate.Secret(sql.FieldLT(FieldCurrentVersion, v))
}

// CurrentVersionLTE applies the LTE predicate on the "current_version" field.
func CurrentVersionLTE(v int32) predicate.Secret {
	return predicate.Secret(sql.FieldLTE(FieldCurrentVersion, v))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.Secret {
	return predicate.Secret(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.Secret {
	return predicate.Secret(sql.FieldNotNull(FieldMetadata))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Secret {
	return predicate.Secret(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Secret {
	return predicate.Secret(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Secret {
	return predicate.Secret(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Secret {
	return predicate.Secret(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Secret {
	return predicate.Secret(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Secret {
	return predicate.Secret(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Secret {
	return predicate.Secret(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Secret {
	return predicate.Secret(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Secret {
	return predicate.Secret(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Secret {
	return predicate.Secret(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Secret {
	return predicate.Secret(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Secret {
	return predicate.Secret(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Secret {
	return predicate.Secret(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Secret {
	return predicate.Secret(sql.FieldContainsFold(FieldDescription, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Secret {
	return predicate.Secret(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Secret {
	return predicate.Secret(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Secret {
	return predicate.Secret(sql.FieldNotIn(FieldStatus, vs...))
}

// HasFolder applies the HasEdge predicate on the "folder" edge.
func HasFolder() predicate.Secret {
	return predicate.Secret(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, FolderTable, FolderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFolderWith applies the HasEdge predicate on the "folder" edge with a given conditions (other predicates).
func HasFolderWith(preds ...predicate.Folder) predicate.Secret {
	return predicate.Secret(func(s *sql.Selector) {
		step := newFolderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasVersions applies the HasEdge predicate on the "versions" edge.
func HasVersions() predicate.Secret {
	return predicate.Secret(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, VersionsTable, VersionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasVersionsWith applies the HasEdge predicate on the "versions" edge with a given conditions (other predicates).
func HasVersionsWith(preds ...predicate.SecretVersion) predicate.Secret {
	return predicate.Secret(func(s *sql.Selector) {
		step := newVersionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPermissions applies the HasEdge predicate on the "permissions" edge.
func HasPermissions() predicate.Secret {
	return predicate.Secret(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PermissionsTable, PermissionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPermissionsWith applies the HasEdge predicate on the "permissions" edge with a given conditions (other predicates).
func HasPermissionsWith(preds ...predicate.Permission) predicate.Secret {
	return predicate.Secret(func(s *sql.Selector) {
		step := newPermissionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Secret) predicate.Secret {
	return predicate.Secret(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Secret) predicate.Secret {
	return predicate.Secret(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Secret) predicate.Secret {
	return predicate.Secret(sql.NotPredicates(p))
}
