// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// WardenAuditLogsColumns holds the columns for the "warden_audit_logs" table.
	WardenAuditLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true, Comment: "id"},
		{Name: "create_time", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "update_time", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "delete_time", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID", Default: 0},
		{Name: "audit_id", Type: field.TypeString, Unique: true, Comment: "Unique audit log identifier (UUID)"},
		{Name: "request_id", Type: field.TypeString, Nullable: true, Comment: "Request ID from metadata"},
		{Name: "operation", Type: field.TypeString, Comment: "gRPC operation path"},
		{Name: "service_name", Type: field.TypeString, Comment: "Service name", Default: "warden-service"},
		{Name: "client_id", Type: field.TypeString, Nullable: true, Comment: "Client ID from certificate CN"},
		{Name: "client_common_name", Type: field.TypeString, Nullable: true, Comment: "Client certificate common name"},
		{Name: "client_organization", Type: field.TypeString, Nullable: true, Comment: "Client certificate organization"},
		{Name: "client_serial_number", Type: field.TypeString, Nullable: true, Comment: "Client certificate serial number"},
		{Name: "is_authenticated", Type: field.TypeBool, Comment: "Whether the client was authenticated via mTLS", Default: false},
		{Name: "success", Type: field.TypeBool, Comment: "Whether the operation succeeded", Default: true},
		{Name: "error_code", Type: field.TypeInt32, Nullable: true, Comment: "Error code if failed"},
		{Name: "error_message", Type: field.TypeString, Nullable: true, Comment: "Error message if failed"},
		{Name: "latency_ms", Type: field.TypeInt64, Comment: "Operation latency in milliseconds", Default: 0},
		{Name: "peer_address", Type: field.TypeString, Nullable: true, Comment: "Client IP address"},
		{Name: "geo_location", Type: field.TypeJSON, Nullable: true, Comment: "Geographic location info"},
		{Name: "log_hash", Type: field.TypeString, Nullable: true, Comment: "SHA-256 hash of the log content"},
		{Name: "signature", Type: field.TypeBytes, Nullable: true, Comment: "ECDSA signature for integrity verification"},
		{Name: "metadata", Type: field.TypeJSON, Nullable: true, Comment: "Additional metadata"},
	}
	// WardenAuditLogsTable holds the schema information for the "warden_audit_logs" table.
	WardenAuditLogsTable = &schema.Table{
		Name:       "warden_audit_logs",
		Columns:    WardenAuditLogsColumns,
		PrimaryKey: []*schema.Column{WardenAuditLogsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "warden_auditlog_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{WardenAuditLogsColumns[4]},
			},
			{
				Name:    "warden_auditlog_tenant_client",
				Unique:  false,
				Columns: []*schema.Column{WardenAuditLogsColumns[4], WardenAuditLogsColumns[9]},
			},
			{
				Name:    "warden_auditlog_tenant_operation",
				Unique:  false,
				Columns: []*schema.Column{WardenAuditLogsColumns[4], WardenAuditLogsColumns[7]},
			},
			{
				Name:    "warden_auditlog_tenant_success",
				Unique:  false,
				Columns: []*schema.Column{WardenAuditLogsColumns[4], WardenAuditLogsColumns[14]},
			},
			{
				Name:    "warden_auditlog_operation",
				Unique:  false,
				Columns: []*schema.Column{WardenAuditLogsColumns[7]},
			},
			{
				Name:    "warden_auditlog_client_id",
				Unique:  false,
				Columns: []*schema.Column{WardenAuditLogsColumns[9]},
			},
			{
				Name:    "warden_auditlog_success",
				Unique:  false,
				Columns: []*schema.Column{WardenAuditLogsColumns[14]},
			},
			{
				Name:    "warden_auditlog_peer_address",
				Unique:  false,
				Columns: []*schema.Column{WardenAuditLogsColumns[18]},
			},
		},
	}
	// WardenFoldersColumns holds the columns for the "warden_folders" table.
	WardenFoldersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Comment: "UUID primary key"},
		{Name: "create_by", Type: field.TypeUint32, Nullable: true, Comment: "创建者ID"},
		{Name: "create_time", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "update_time", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "delete_time", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID", Default: 0},
		{Name: "name", Type: field.TypeString, Size: 255, Comment: "Folder name"},
		{Name: "path", Type: field.TypeString, Size: 4096, Comment: "Materialized path (e.g., /root/sub/current)"},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 1024, Comment: "Optional description"},
		{Name: "depth", Type: field.TypeInt32, Comment: "Nesting depth level (0 for root folders)", Default: 0},
		{Name: "parent_id", Type: field.TypeString, Nullable: true, Comment: "Parent folder ID (null for root-level folders)"},
	}
	// WardenFoldersTable holds the schema information for the "warden_folders" table.
	WardenFoldersTable = &schema.Table{
		Name:       "warden_folders",
		Columns:    WardenFoldersColumns,
		PrimaryKey: []*schema.Column{WardenFoldersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "warden_folders_warden_folders_children",
				Columns:    []*schema.Column{WardenFoldersColumns[10]},
				RefColumns: []*schema.Column{WardenFoldersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "folder_tenant_id_parent_id_name",
				Unique:  true,
				Columns: []*schema.Column{WardenFoldersColumns[5], WardenFoldersColumns[10], WardenFoldersColumns[6]},
			},
			{
				Name:    "folder_tenant_id_path",
				Unique:  true,
				Columns: []*schema.Column{WardenFoldersColumns[5], WardenFoldersColumns[7]},
			},
			{
				Name:    "folder_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{WardenFoldersColumns[5]},
			},
			{
				Name:    "folder_parent_id",
				Unique:  false,
				Columns: []*schema.Column{WardenFoldersColumns[10]},
			},
			{
				Name:    "folder_path",
				Unique:  false,
				Columns: []*schema.Column{WardenFoldersColumns[7]},
			},
		},
	}
	// WardenPermissionsColumns holds the columns for the "warden_permissions" table.
	WardenPermissionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "update_time", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "delete_time", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID", Default: 0},
		{Name: "resource_type", Type: field.TypeEnum, Comment: "Type of resource (folder or secret)", Enums: []string{"RESOURCE_TYPE_UNSPECIFIED", "RESOURCE_TYPE_FOLDER", "RESOURCE_TYPE_SECRET"}},
		{Name: "resource_id", Type: field.TypeString, Size: 36, Comment: "ID of the folder or secret"},
		{Name: "relation", Type: field.TypeEnum, Comment: "Permission level (owner, editor, viewer, sharer)", Enums: []string{"RELATION_UNSPECIFIED", "RELATION_OWNER", "RELATION_EDITOR", "RELATION_VIEWER", "RELATION_SHARER"}},
		{Name: "subject_type", Type: field.TypeEnum, Comment: "Type of subject (user, role, or tenant)", Enums: []string{"SUBJECT_TYPE_UNSPECIFIED", "SUBJECT_TYPE_USER", "SUBJECT_TYPE_ROLE", "SUBJECT_TYPE_TENANT"}},
		{Name: "subject_id", Type: field.TypeString, Size: 36, Comment: "ID of the user, role, or tenant"},
		{Name: "granted_by", Type: field.TypeUint32, Nullable: true, Comment: "User ID who granted this permission"},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true, Comment: "Optional expiration time for temporary access"},
		{Name: "folder_permissions", Type: field.TypeString, Nullable: true},
		{Name: "secret_permissions", Type: field.TypeString, Nullable: true},
	}
	// WardenPermissionsTable holds the schema information for the "warden_permissions" table.
	WardenPermissionsTable = &schema.Table{
		Name:       "warden_permissions",
		Columns:    WardenPermissionsColumns,
		PrimaryKey: []*schema.Column{WardenPermissionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "warden_permissions_warden_folders_permissions",
				Columns:    []*schema.Column{WardenPermissionsColumns[12]},
				RefColumns: []*schema.Column{WardenFoldersColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "warden_permissions_warden_secrets_permissions",
				Columns:    []*schema.Column{WardenPermissionsColumns[13]},
				RefColumns: []*schema.Column{WardenSecretsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "permission_tenant_id_resource_type_resource_id_relation_subject_type_subject_id",
				Unique:  true,
				Columns: []*schema.Column{WardenPermissionsColumns[4], WardenPermissionsColumns[5], WardenPermissionsColumns[6], WardenPermissionsColumns[7], WardenPermissionsColumns[8], WardenPermissionsColumns[9]},
			},
			{
				Name:    "permission_tenant_id_resource_type_resource_id",
				Unique:  false,
				Columns: []*schema.Column{WardenPermissionsColumns[4], WardenPermissionsColumns[5], WardenPermissionsColumns[6]},
			},
			{
				Name:    "permission_subject_type_subject_id",
				Unique:  false,
				Columns: []*schema.Column{WardenPermissionsColumns[8], WardenPermissionsColumns[9]},
			},
			{
				Name:    "permission_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{WardenPermissionsColumns[4]},
			},
			{
				Name:    "permission_expires_at",
				Unique:  false,
				Columns: []*schema.Column{WardenPermissionsColumns[11]},
			},
		},
	}
	// WardenSecretsColumns holds the columns for the "warden_secrets" table.
	WardenSecretsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Comment: "UUID primary key"},
		{Name: "create_by", Type: field.TypeUint32, Nullable: true, Comment: "创建者ID"},
		{Name: "update_by", Type: field.TypeUint32, Nullable: true, Comment: "更新者ID"},
		{Name: "create_time", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "update_time", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "delete_time", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID", Default: 0},
		{Name: "name", Type: field.TypeString, Size: 255, Comment: "Secret name"},
		{Name: "username", Type: field.TypeString, Nullable: true, Size: 255, Comment: "Associated username"},
		{Name: "host_url", Type: field.TypeString, Nullable: true, Size: 2048, Comment: "Host/URL associated with the secret"},
		{Name: "vault_path", Type: field.TypeString, Comment: "Reference path to HashiCorp Vault"},
		{Name: "current_version", Type: field.TypeInt32, Comment: "Current active version number", Default: 1},
		{Name: "metadata", Type: field.TypeJSON, Nullable: true, Comment: "Custom fields, notes, tags (JSON)"},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 4096, Comment: "Description"},
		{Name: "status", Type: field.TypeEnum, Comment: "Secret status", Enums: []string{"SECRET_STATUS_UNSPECIFIED", "SECRET_STATUS_ACTIVE", "SECRET_STATUS_ARCHIVED", "SECRET_STATUS_DELETED"}, Default: "SECRET_STATUS_ACTIVE"},
		{Name: "folder_id", Type: field.TypeString, Nullable: true, Comment: "Parent folder ID (null for root-level secrets)"},
	}
	// WardenSecretsTable holds the schema information for the "warden_secrets" table.
	WardenSecretsTable = &schema.Table{
		Name:       "warden_secrets",
		Columns:    WardenSecretsColumns,
		PrimaryKey: []*schema.Column{WardenSecretsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "warden_secrets_warden_folders_secrets",
				Columns:    []*schema.Column{WardenSecretsColumns[15]},
				RefColumns: []*schema.Column{WardenFoldersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "secret_tenant_id_folder_id_name",
				Unique:  true,
				Columns: []*schema.Column{WardenSecretsColumns[6], WardenSecretsColumns[15], WardenSecretsColumns[7]},
			},
			{
				Name:    "secret_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{WardenSecretsColumns[6]},
			},
			{
				Name:    "secret_folder_id",
				Unique:  false,
				Columns: []*schema.Column{WardenSecretsColumns[15]},
			},
			{
				Name:    "secret_tenant_id_name",
				Unique:  false,
				Columns: []*schema.Column{WardenSecretsColumns[6], WardenSecretsColumns[7]},
			},
			{
				Name:    "secret_tenant_id_username",
				Unique:  false,
				Columns: []*schema.Column{WardenSecretsColumns[6], WardenSecretsColumns[8]},
			},
			{
				Name:    "secret_status",
				Unique:  false,
				Columns: []*schema.Column{WardenSecretsColumns[14]},
			},
			{
				Name:    "secret_vault_path",
				Unique:  true,
				Columns: []*schema.Column{WardenSecretsColumns[10]},
			},
		},
	}
	// WardenSecretVersionsColumns holds the columns for the "warden_secret_versions" table.
	WardenSecretVersionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_by", Type: field.TypeUint32, Nullable: true, Comment: "创建者ID"},
		{Name: "create_time", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "update_time", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "delete_time", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "version_number", Type: field.TypeInt32, Comment: "Version number (1, 2, 3...)"},
		{Name: "vault_path", Type: field.TypeString, Comment: "Vault path for this version"},
		{Name: "comment", Type: field.TypeString, Nullable: true, Size: 1024, Comment: "Version comment describing the change"},
		{Name: "checksum", Type: field.TypeString, Size: 64, Comment: "SHA-256 checksum of the password"},
		{Name: "secret_id", Type: field.TypeString, Comment: "Parent secret ID"},
	}
	// WardenSecretVersionsTable holds the schema information for the "warden_secret_versions" table.
	WardenSecretVersionsTable = &schema.Table{
		Name:       "warden_secret_versions",
		Columns:    WardenSecretVersionsColumns,
		PrimaryKey: []*schema.Column{WardenSecretVersionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "warden_secret_versions_warden_secrets_versions",
				Columns:    []*schema.Column{WardenSecretVersionsColumns[9]},
				RefColumns: []*schema.Column{WardenSecretsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "secretversion_secret_id_version_number",
				Unique:  true,
				Columns: []*schema.Column{WardenSecretVersionsColumns[9], WardenSecretVersionsColumns[5]},
			},
			{
				Name:    "secretversion_secret_id",
				Unique:  false,
				Columns: []*schema.Column{WardenSecretVersionsColumns[9]},
			},
			{
				Name:    "secretversion_vault_path",
				Unique:  true,
				Columns: []*schema.Column{WardenSecretVersionsColumns[6]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		WardenAuditLogsTable,
		WardenFoldersTable,
		WardenPermissionsTable,
		WardenSecretsTable,
		WardenSecretVersionsTable,
	}
)

func init() {
	WardenAuditLogsTable.Annotation = &entsql.Annotation{
		Table: "warden_audit_logs",
	}
	WardenFoldersTable.ForeignKeys[0].RefTable = WardenFoldersTable
	WardenFoldersTable.Annotation = &entsql.Annotation{
		Table: "warden_folders",
	}
	WardenPermissionsTable.ForeignKeys[0].RefTable = WardenFoldersTable
	WardenPermissionsTable.ForeignKeys[1].RefTable = WardenSecretsTable
	WardenPermissionsTable.Annotation = &entsql.Annotation{
		Table: "warden_permissions",
	}
	WardenSecretsTable.ForeignKeys[0].RefTable = WardenFoldersTable
	WardenSecretsTable.Annotation = &entsql.Annotation{
		Table: "warden_secrets",
	}
	WardenSecretVersionsTable.ForeignKeys[0].RefTable = WardenSecretsTable
	WardenSecretVersionsTable.Annotation = &entsql.Annotation{
		Table: "warden_secret_versions",
	}
}
