// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-tangra/go-tangra-warden/internal/cert"
	"github.com/go-tangra/go-tangra-warden/internal/data"
	"github.com/go-tangra/go-tangra-warden/internal/server"
	"github.com/go-tangra/go-tangra-warden/internal/service"
	"github.com/go-tangra/go-tangra-warden/internal/service/providers"
	"github.com/tx7do/kratos-bootstrap/bootstrap"
)

// Injectors from wire.go:

// initApp initializes the Wire provider entry for the kratos application
func initApp(context *bootstrap.Context) (*kratos.App, func(), error) {
	certManager, err := cert.NewCertManager(context)
	if err != nil {
		return nil, nil, err
	}
	entClient, cleanup, err := data.NewEntClient(context)
	if err != nil {
		return nil, nil, err
	}
	auditLogRepo := data.NewAuditLogRepo(context, entClient)
	folderRepo := data.NewFolderRepo(context, entClient)
	permissionRepo := data.NewPermissionRepo(context, entClient)
	permissionStore := providers.ProvidePermissionStore(permissionRepo)
	secretRepo := data.NewSecretRepo(context, entClient)
	resourceLookup := providers.ProvideResourceLookup(folderRepo, secretRepo)
	engine := providers.ProvideAuthzEngine(permissionStore, resourceLookup, context)
	checker := providers.ProvideAuthzChecker(engine)
	folderService := service.NewFolderService(context, folderRepo, permissionRepo, checker)
	secretVersionRepo := data.NewSecretVersionRepo(context, entClient)
	client, cleanup2, err := data.NewVaultClient(context)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	kvStore := data.NewVaultKVStore(client)
	secretService := service.NewSecretService(context, secretRepo, secretVersionRepo, folderRepo, permissionRepo, kvStore, checker)
	permissionService := service.NewPermissionService(context, permissionRepo, folderRepo, secretRepo, engine, checker)
	statisticsRepo := data.NewStatisticsRepo(context, entClient)
	systemService := service.NewSystemService(context, client, statisticsRepo)
	bitwardenTransferService := service.NewBitwardenTransferService(context, secretRepo, folderRepo, secretVersionRepo, permissionRepo, kvStore, checker)
	backupService := service.NewBackupService(context, entClient, kvStore)
	grpcServer := server.NewGRPCServer(context, certManager, auditLogRepo, folderService, secretService, permissionService, systemService, bitwardenTransferService, backupService)
	app := newApp(context, grpcServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
