// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-tangra/go-tangra-warden/internal/cert"
	"github.com/go-tangra/go-tangra-warden/internal/client"
	"github.com/go-tangra/go-tangra-warden/internal/data"
	"github.com/go-tangra/go-tangra-warden/internal/metrics"
	"github.com/go-tangra/go-tangra-warden/internal/server"
	"github.com/go-tangra/go-tangra-warden/internal/service"
	"github.com/go-tangra/go-tangra-warden/internal/service/providers"
	"github.com/tx7do/kratos-bootstrap/bootstrap"
)

// Injectors from wire.go:

// initApp initializes the Wire provider entry for the kratos application
func initApp(context *bootstrap.Context) (*kratos.App, func(), error) {
	certManager, err := cert.NewCertManager(context)
	if err != nil {
		return nil, nil, err
	}
	collector := metrics.NewCollector(context)
	entClient, cleanup, err := data.NewEntClient(context)
	if err != nil {
		return nil, nil, err
	}
	auditLogRepo := data.NewAuditLogRepo(context, entClient)
	folderRepo := data.NewFolderRepo(context, entClient)
	secretRepo := data.NewSecretRepo(context, entClient)
	secretVersionRepo := data.NewSecretVersionRepo(context, entClient)
	permissionRepo := data.NewPermissionRepo(context, entClient)
	vaultClient, cleanup2, err := data.NewVaultClient(context)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	kvStore := data.NewVaultKVStore(vaultClient)
	permissionStore := providers.ProvidePermissionStore(permissionRepo)
	resourceLookup := providers.ProvideResourceLookup(folderRepo, secretRepo)
	engine := providers.ProvideAuthzEngine(permissionStore, resourceLookup, context)
	checker := providers.ProvideAuthzChecker(engine)
	folderService := service.NewFolderService(context, folderRepo, secretRepo, secretVersionRepo, permissionRepo, kvStore, checker, collector)
	secretService := service.NewSecretService(context, secretRepo, secretVersionRepo, folderRepo, permissionRepo, kvStore, checker, collector)
	permissionService := service.NewPermissionService(context, permissionRepo, folderRepo, secretRepo, engine, checker)
	statisticsRepo := data.NewStatisticsRepo(context, entClient)
	sharingClient, cleanup3, err := client.NewSharingClient(context, certManager)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	systemService := service.NewSystemService(context, vaultClient, statisticsRepo, sharingClient)
	bitwardenTransferService := service.NewBitwardenTransferService(context, secretRepo, folderRepo, secretVersionRepo, permissionRepo, kvStore, checker, collector)
	backupService := service.NewBackupService(context, entClient, kvStore)
	sqlBackupService := service.NewSqlBackupService(context, entClient, kvStore)
	adminClient, cleanup4, err := client.NewAdminClient(context, certManager)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	userService := service.NewUserService(context, adminClient)
	grpcServer := server.NewGRPCServer(context, certManager, collector, auditLogRepo, folderService, secretService, permissionService, systemService, bitwardenTransferService, backupService, sqlBackupService, userService)
	httpServer := server.NewHTTPServer(context)
	app := newApp(context, grpcServer, httpServer)
	return app, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
