// Code generated by ent, DO NOT EDIT.

package permission

import (
	"fmt"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the permission type in the database.
	Label = "permission"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldDeleteTime holds the string denoting the delete_time field in the database.
	FieldDeleteTime = "delete_time"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldResourceType holds the string denoting the resource_type field in the database.
	FieldResourceType = "resource_type"
	// FieldResourceID holds the string denoting the resource_id field in the database.
	FieldResourceID = "resource_id"
	// FieldRelation holds the string denoting the relation field in the database.
	FieldRelation = "relation"
	// FieldSubjectType holds the string denoting the subject_type field in the database.
	FieldSubjectType = "subject_type"
	// FieldSubjectID holds the string denoting the subject_id field in the database.
	FieldSubjectID = "subject_id"
	// FieldGrantedBy holds the string denoting the granted_by field in the database.
	FieldGrantedBy = "granted_by"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// EdgeFolder holds the string denoting the folder edge name in mutations.
	EdgeFolder = "folder"
	// EdgeSecret holds the string denoting the secret edge name in mutations.
	EdgeSecret = "secret"
	// Table holds the table name of the permission in the database.
	Table = "warden_permissions"
	// FolderTable is the table that holds the folder relation/edge.
	FolderTable = "warden_permissions"
	// FolderInverseTable is the table name for the Folder entity.
	// It exists in this package in order to avoid circular dependency with the "folder" package.
	FolderInverseTable = "warden_folders"
	// FolderColumn is the table column denoting the folder relation/edge.
	FolderColumn = "folder_permissions"
	// SecretTable is the table that holds the secret relation/edge.
	SecretTable = "warden_permissions"
	// SecretInverseTable is the table name for the Secret entity.
	// It exists in this package in order to avoid circular dependency with the "secret" package.
	SecretInverseTable = "warden_secrets"
	// SecretColumn is the table column denoting the secret relation/edge.
	SecretColumn = "secret_permissions"
)

// Columns holds all SQL columns for permission fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldDeleteTime,
	FieldTenantID,
	FieldResourceType,
	FieldResourceID,
	FieldRelation,
	FieldSubjectType,
	FieldSubjectID,
	FieldGrantedBy,
	FieldExpiresAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "warden_permissions"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"folder_permissions",
	"secret_permissions",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/go-tangra/go-tangra-warden/internal/data/ent/runtime"
var (
	Hooks  [1]ent.Hook
	Policy ent.Policy
	// DefaultTenantID holds the default value on creation for the "tenant_id" field.
	DefaultTenantID uint32
	// ResourceIDValidator is a validator for the "resource_id" field. It is called by the builders before save.
	ResourceIDValidator func(string) error
	// SubjectIDValidator is a validator for the "subject_id" field. It is called by the builders before save.
	SubjectIDValidator func(string) error
)

// ResourceType defines the type for the "resource_type" enum field.
type ResourceType string

// ResourceType values.
const (
	ResourceTypeRESOURCE_TYPE_UNSPECIFIED ResourceType = "RESOURCE_TYPE_UNSPECIFIED"
	ResourceTypeRESOURCE_TYPE_FOLDER      ResourceType = "RESOURCE_TYPE_FOLDER"
	ResourceTypeRESOURCE_TYPE_SECRET      ResourceType = "RESOURCE_TYPE_SECRET"
)

func (rt ResourceType) String() string {
	return string(rt)
}

// ResourceTypeValidator is a validator for the "resource_type" field enum values. It is called by the builders before save.
func ResourceTypeValidator(rt ResourceType) error {
	switch rt {
	case ResourceTypeRESOURCE_TYPE_UNSPECIFIED, ResourceTypeRESOURCE_TYPE_FOLDER, ResourceTypeRESOURCE_TYPE_SECRET:
		return nil
	default:
		return fmt.Errorf("permission: invalid enum value for resource_type field: %q", rt)
	}
}

// Relation defines the type for the "relation" enum field.
type Relation string

// Relation values.
const (
	RelationRELATION_UNSPECIFIED Relation = "RELATION_UNSPECIFIED"
	RelationRELATION_OWNER       Relation = "RELATION_OWNER"
	RelationRELATION_EDITOR      Relation = "RELATION_EDITOR"
	RelationRELATION_VIEWER      Relation = "RELATION_VIEWER"
	RelationRELATION_SHARER      Relation = "RELATION_SHARER"
)

func (r Relation) String() string {
	return string(r)
}

// RelationValidator is a validator for the "relation" field enum values. It is called by the builders before save.
func RelationValidator(r Relation) error {
	switch r {
	case RelationRELATION_UNSPECIFIED, RelationRELATION_OWNER, RelationRELATION_EDITOR, RelationRELATION_VIEWER, RelationRELATION_SHARER:
		return nil
	default:
		return fmt.Errorf("permission: invalid enum value for relation field: %q", r)
	}
}

// SubjectType defines the type for the "subject_type" enum field.
type SubjectType string

// SubjectType values.
const (
	SubjectTypeSUBJECT_TYPE_UNSPECIFIED SubjectType = "SUBJECT_TYPE_UNSPECIFIED"
	SubjectTypeSUBJECT_TYPE_USER        SubjectType = "SUBJECT_TYPE_USER"
	SubjectTypeSUBJECT_TYPE_ROLE        SubjectType = "SUBJECT_TYPE_ROLE"
	SubjectTypeSUBJECT_TYPE_TENANT      SubjectType = "SUBJECT_TYPE_TENANT"
)

func (st SubjectType) String() string {
	return string(st)
}

// SubjectTypeValidator is a validator for the "subject_type" field enum values. It is called by the builders before save.
func SubjectTypeValidator(st SubjectType) error {
	switch st {
	case SubjectTypeSUBJECT_TYPE_UNSPECIFIED, SubjectTypeSUBJECT_TYPE_USER, SubjectTypeSUBJECT_TYPE_ROLE, SubjectTypeSUBJECT_TYPE_TENANT:
		return nil
	default:
		return fmt.Errorf("permission: invalid enum value for subject_type field: %q", st)
	}
}

// OrderOption defines the ordering options for the Permission queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByDeleteTime orders the results by the delete_time field.
func ByDeleteTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeleteTime, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByResourceType orders the results by the resource_type field.
func ByResourceType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResourceType, opts...).ToFunc()
}

// ByResourceID orders the results by the resource_id field.
func ByResourceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResourceID, opts...).ToFunc()
}

// ByRelation orders the results by the relation field.
func ByRelation(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRelation, opts...).ToFunc()
}

// BySubjectType orders the results by the subject_type field.
func BySubjectType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubjectType, opts...).ToFunc()
}

// BySubjectID orders the results by the subject_id field.
func BySubjectID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubjectID, opts...).ToFunc()
}

// ByGrantedBy orders the results by the granted_by field.
func ByGrantedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGrantedBy, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByFolderField orders the results by folder field.
func ByFolderField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFolderStep(), sql.OrderByField(field, opts...))
	}
}

// BySecretField orders the results by secret field.
func BySecretField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSecretStep(), sql.OrderByField(field, opts...))
	}
}
func newFolderStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FolderInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, FolderTable, FolderColumn),
	)
}
func newSecretStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SecretInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SecretTable, SecretColumn),
	)
}
