// Code generated by ent, DO NOT EDIT.

package secretversion

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the secretversion type in the database.
	Label = "secret_version"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateBy holds the string denoting the create_by field in the database.
	FieldCreateBy = "create_by"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldDeleteTime holds the string denoting the delete_time field in the database.
	FieldDeleteTime = "delete_time"
	// FieldSecretID holds the string denoting the secret_id field in the database.
	FieldSecretID = "secret_id"
	// FieldVersionNumber holds the string denoting the version_number field in the database.
	FieldVersionNumber = "version_number"
	// FieldVaultPath holds the string denoting the vault_path field in the database.
	FieldVaultPath = "vault_path"
	// FieldComment holds the string denoting the comment field in the database.
	FieldComment = "comment"
	// FieldChecksum holds the string denoting the checksum field in the database.
	FieldChecksum = "checksum"
	// EdgeSecret holds the string denoting the secret edge name in mutations.
	EdgeSecret = "secret"
	// Table holds the table name of the secretversion in the database.
	Table = "warden_secret_versions"
	// SecretTable is the table that holds the secret relation/edge.
	SecretTable = "warden_secret_versions"
	// SecretInverseTable is the table name for the Secret entity.
	// It exists in this package in order to avoid circular dependency with the "secret" package.
	SecretInverseTable = "warden_secrets"
	// SecretColumn is the table column denoting the secret relation/edge.
	SecretColumn = "secret_id"
)

// Columns holds all SQL columns for secretversion fields.
var Columns = []string{
	FieldID,
	FieldCreateBy,
	FieldCreateTime,
	FieldUpdateTime,
	FieldDeleteTime,
	FieldSecretID,
	FieldVersionNumber,
	FieldVaultPath,
	FieldComment,
	FieldChecksum,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// SecretIDValidator is a validator for the "secret_id" field. It is called by the builders before save.
	SecretIDValidator func(string) error
	// VersionNumberValidator is a validator for the "version_number" field. It is called by the builders before save.
	VersionNumberValidator func(int32) error
	// VaultPathValidator is a validator for the "vault_path" field. It is called by the builders before save.
	VaultPathValidator func(string) error
	// CommentValidator is a validator for the "comment" field. It is called by the builders before save.
	CommentValidator func(string) error
	// ChecksumValidator is a validator for the "checksum" field. It is called by the builders before save.
	ChecksumValidator func(string) error
)

// OrderOption defines the ordering options for the SecretVersion queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateBy orders the results by the create_by field.
func ByCreateBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateBy, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByDeleteTime orders the results by the delete_time field.
func ByDeleteTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeleteTime, opts...).ToFunc()
}

// BySecretID orders the results by the secret_id field.
func BySecretID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSecretID, opts...).ToFunc()
}

// ByVersionNumber orders the results by the version_number field.
func ByVersionNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersionNumber, opts...).ToFunc()
}

// ByVaultPath orders the results by the vault_path field.
func ByVaultPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVaultPath, opts...).ToFunc()
}

// ByComment orders the results by the comment field.
func ByComment(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldComment, opts...).ToFunc()
}

// ByChecksum orders the results by the checksum field.
func ByChecksum(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChecksum, opts...).ToFunc()
}

// BySecretField orders the results by secret field.
func BySecretField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSecretStep(), sql.OrderByField(field, opts...))
	}
}
func newSecretStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SecretInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SecretTable, SecretColumn),
	)
}
