// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: warden/v1/warden.proto

package wardenv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_warden_v1_warden_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_warden_v1_warden_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_warden_v1_warden_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Secret struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FolderId       string                 `protobuf:"bytes,2,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	FolderPath     string                 `protobuf:"bytes,3,opt,name=folder_path,json=folderPath,proto3" json:"folder_path,omitempty"`
	Name           string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Username       string                 `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	HostUrl        string                 `protobuf:"bytes,6,opt,name=host_url,json=hostUrl,proto3" json:"host_url,omitempty"`
	Description    string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	CurrentVersion int32                  `protobuf:"varint,8,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"`
	HasTotp        bool                   `protobuf:"varint,9,opt,name=has_totp,json=hasTotp,proto3" json:"has_totp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Secret) Reset() {
	*x = Secret{}
	mi := &file_warden_v1_warden_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Secret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secret) ProtoMessage() {}

func (x *Secret) ProtoReflect() protoreflect.Message {
	mi := &file_warden_v1_warden_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Secret.ProtoReflect.Descriptor instead.
func (*Secret) Descriptor() ([]byte, []int) {
	return file_warden_v1_warden_proto_rawDescGZIP(), []int{1}
}

func (x *Secret) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Secret) GetFolderId() string {
	if x != nil {
		return x.FolderId
	}
	return ""
}

func (x *Secret) GetFolderPath() string {
	if x != nil {
		return x.FolderPath
	}
	return ""
}

func (x *Secret) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Secret) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Secret) GetHostUrl() string {
	if x != nil {
		return x.HostUrl
	}
	return ""
}

func (x *Secret) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Secret) GetCurrentVersion() int32 {
	if x != nil {
		return x.CurrentVersion
	}
	return 0
}

func (x *Secret) GetHasTotp() bool {
	if x != nil {
		return x.HasTotp
	}
	return false
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        *Secret                `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_warden_v1_warden_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_warden_v1_warden_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_warden_v1_warden_proto_rawDescGZIP(), []int{2}
}

func (x *GetResponse) GetSecret() *Secret {
	if x != nil {
		return x.Secret
	}
	return nil
}

type GetPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPasswordRequest) Reset() {
	*x = GetPasswordRequest{}
	mi := &file_warden_v1_warden_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPasswordRequest) ProtoMessage() {}

func (x *GetPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_warden_v1_warden_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPasswordRequest.ProtoReflect.Descriptor instead.
func (*GetPasswordRequest) Descriptor() ([]byte, []int) {
	return file_warden_v1_warden_proto_rawDescGZIP(), []int{3}
}

func (x *GetPasswordRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetPasswordRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type GetPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPasswordResponse) Reset() {
	*x = GetPasswordResponse{}
	mi := &file_warden_v1_warden_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPasswordResponse) ProtoMessage() {}

func (x *GetPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_warden_v1_warden_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPasswordResponse.ProtoReflect.Descriptor instead.
func (*GetPasswordResponse) Descriptor() ([]byte, []int) {
	return file_warden_v1_warden_proto_rawDescGZIP(), []int{4}
}

func (x *GetPasswordResponse) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *GetPasswordResponse) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type CheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceType  string                 `protobuf:"bytes,1,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	ResourceId    string                 `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Permission    string                 `protobuf:"bytes,3,opt,name=permission,proto3" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_warden_v1_warden_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_warden_v1_warden_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_warden_v1_warden_proto_rawDescGZIP(), []int{5}
}

func (x *CheckRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *CheckRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *CheckRequest) GetPermission() string {
	if x != nil {
		return x.Permission
	}
	return ""
}

type CheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Relation      string                 `protobuf:"bytes,2,opt,name=relation,proto3" json:"relation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_warden_v1_warden_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_warden_v1_warden_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_warden_v1_warden_proto_rawDescGZIP(), []int{6}
}

func (x *CheckResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckResponse) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

var File_warden_v1_warden_proto protoreflect.FileDescriptor

const file_warden_v1_warden_proto_rawDesc = "" +
	"\n" +
	"\x16warden/v1/warden.proto\x12\twarden.v1\"\x1c\n" +
	"\n" +
	"GetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x87\x02\n" +
	"\x06Secret\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tfolder_id\x18\x02 \x01(\tR\bfolderId\x12\x1f\n" +
	"\vfolder_path\x18\x03 \x01(\tR\n" +
	"folderPath\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1a\n" +
	"\busername\x18\x05 \x01(\tR\busername\x12\x19\n" +
	"\bhost_url\x18\x06 \x01(\tR\ahostUrl\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12'\n" +
	"\x0fcurrent_version\x18\b \x01(\x05R\x0ecurrentVersion\x12\x19\n" +
	"\bhas_totp\x18\t \x01(\bR\ahasTotp\"8\n" +
	"\vGetResponse\x12)\n" +
	"\x06secret\x18\x01 \x01(\v2\x11.warden.v1.SecretR\x06secret\">\n" +
	"\x12GetPasswordRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\"K\n" +
	"\x13GetPasswordResponse\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\"t\n" +
	"\fCheckRequest\x12#\n" +
	"\rresource_type\x18\x01 \x01(\tR\fresourceType\x12\x1f\n" +
	"\vresource_id\x18\x02 \x01(\tR\n" +
	"resourceId\x12\x1e\n" +
	"\n" +
	"permission\x18\x03 \x01(\tR\n" +
	"permission\"E\n" +
	"\rCheckResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x1a\n" +
	"\brelation\x18\x02 \x01(\tR\brelation2\xc9\x01\n" +
	"\aSecrets\x124\n" +
	"\x03Get\x12\x15.warden.v1.GetRequest\x1a\x16.warden.v1.GetResponse\x12L\n" +
	"\vGetPassword\x12\x1d.warden.v1.GetPasswordRequest\x1a\x1e.warden.v1.GetPasswordResponse\x12:\n" +
	"\x05Check\x12\x17.warden.v1.CheckRequest\x1a\x18.warden.v1.CheckResponseBHZFgithub.com/go-freya/freya/services/warden/api/proto/warden/v1;wardenv1b\x06proto3"

var (
	file_warden_v1_warden_proto_rawDescOnce sync.Once
	file_warden_v1_warden_proto_rawDescData []byte
)

func file_warden_v1_warden_proto_rawDescGZIP() []byte {
	file_warden_v1_warden_proto_rawDescOnce.Do(func() {
		file_warden_v1_warden_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_warden_v1_warden_proto_rawDesc), len(file_warden_v1_warden_proto_rawDesc)))
	})
	return file_warden_v1_warden_proto_rawDescData
}

var file_warden_v1_warden_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_warden_v1_warden_proto_goTypes = []any{
	(*GetRequest)(nil),          // 0: warden.v1.GetRequest
	(*Secret)(nil),              // 1: warden.v1.Secret
	(*GetResponse)(nil),         // 2: warden.v1.GetResponse
	(*GetPasswordRequest)(nil),  // 3: warden.v1.GetPasswordRequest
	(*GetPasswordResponse)(nil), // 4: warden.v1.GetPasswordResponse
	(*CheckRequest)(nil),        // 5: warden.v1.CheckRequest
	(*CheckResponse)(nil),       // 6: warden.v1.CheckResponse
}
var file_warden_v1_warden_proto_depIdxs = []int32{
	1, // 0: warden.v1.GetResponse.secret:type_name -> warden.v1.Secret
	0, // 1: warden.v1.Secrets.Get:input_type -> warden.v1.GetRequest
	3, // 2: warden.v1.Secrets.GetPassword:input_type -> warden.v1.GetPasswordRequest
	5, // 3: warden.v1.Secrets.Check:input_type -> warden.v1.CheckRequest
	2, // 4: warden.v1.Secrets.Get:output_type -> warden.v1.GetResponse
	4, // 5: warden.v1.Secrets.GetPassword:output_type -> warden.v1.GetPasswordResponse
	6, // 6: warden.v1.Secrets.Check:output_type -> warden.v1.CheckResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_warden_v1_warden_proto_init() }
func file_warden_v1_warden_proto_init() {
	if File_warden_v1_warden_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_warden_v1_warden_proto_rawDesc), len(file_warden_v1_warden_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_warden_v1_warden_proto_goTypes,
		DependencyIndexes: file_warden_v1_warden_proto_depIdxs,
		MessageInfos:      file_warden_v1_warden_proto_msgTypes,
	}.Build()
	File_warden_v1_warden_proto = out.File
	file_warden_v1_warden_proto_goTypes = nil
	file_warden_v1_warden_proto_depIdxs = nil
}
